test_cfg = {
    "wm2_check_wifi_credential_config": [
        {},
    ],
    "wm2_connect_wpa3_client": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5g",
        },
        {
            "channel": 101,
            "ht_mode": "HT40",
            "radio_band": "6g",
        },
    ],
    "wm2_connect_wpa3_leaf": [
        {
            "channel": 6,
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channel": 44,
            "ht_mode": "HT40",
            "radio_band": "5g",
        },
        {
            "channel": 101,
            "ht_mode": "HT80",
            "radio_band": "6g",
        },
    ],
    "wm2_create_all_aps_per_radio": [
        {
            "channel": 6,
            "ht_mode": "HT20",
            "radio_band": "24g",
            "vif_config": {
                "backhaul_ap": ["b-ap-24", 1],
                "home_ap": ["home-ap-24", 2],
                "onboard_ap": ["onboard-ap-24", 3],
                "auxillary_ap_1": ["aux-ap-124", 4],
                "auxillary_ap_2": ["aux-ap-224", 5],
                "fronthaul_ap": ["fhaul-ap-24", 6],
                "captive_portal": ["cportal-ap-24", 7],
            },
        },
        {
            "channel": 44,
            "ht_mode": "HT80",
            "radio_band": "5g",
            "vif_config": {
                "backhaul_ap": ["b-ap-50", 1],
                "home_ap": ["home-ap-50", 2],
                "onboard_ap": ["onboard-ap-50", 3],
                "auxillary_ap_1": ["aux-ap-150", 4],
                "auxillary_ap_2": ["aux-ap-250", 5],
                "fronthaul_ap": ["fhaul-ap-50", 6],
                "captive_portal": ["cportal-ap-50", 7],
            },
        },
        {
            "channel": 101,
            "encryption": "WPA3",
            "ht_mode": "HT80",
            "radio_band": "6g",
            "vif_config": {
                "backhaul_ap": ["b-ap-60", 1],
                "home_ap": ["home-ap-60", 2],
                "onboard_ap": ["onboard-ap-60", 3],
                "auxillary_ap_1": ["aux-ap-160", 4],
                "auxillary_ap_2": ["aux-ap-260", 5],
                "fronthaul_ap": ["fhaul-ap-60", 6],
                "captive_portal": ["cportal-ap-60", 7],
            },
        },
    ],
    "wm2_create_wpa3_ap": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "interface_type": "home_ap",
            "radio_band": "24g",
        },
        {
            "channel": 6,
            "ht_mode": "HT40",
            "interface_type": "backhaul_ap",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT20",
            "interface_type": "home_ap",
            "radio_band": "5g",
        },
        {
            "channel": 36,
            "ht_mode": "HT20",
            "interface_type": "backhaul_ap",
            "radio_band": "5g",
        },
        {
            "channel": 101,
            "ht_mode": "HT20",
            "interface_type": "home_ap",
            "radio_band": "6g",
        },
        {
            "channel": 101,
            "ht_mode": "HT20",
            "interface_type": "backhaul_ap",
            "radio_band": "6g",
        },
    ],
    "wm2_dfs_cac_aborted": [
        {
            "channel_A": 52,
            "channel_B": 60,
            "ht_mode": "HT20",
            "radio_band": "5g",
        },
    ],
    "wm2_pre_cac_channel_change_validation": [
        {
            'channel_A': 52,
            'channel_B': 60,
            'ht_mode': 'HT40',
            'radio_band': '5g',
        },
        {
            'channel_A': 44,
            'channel_B': 56,
            'ht_mode': 'HT80',
            'radio_band': '5g',
        },
        {
            'channel_A': 40,
            'channel_B': 60,
            'ht_mode': 'HT80',
            'radio_band': '5g',
        },
        {
            'channel_A': 100,
            'channel_B': 108,
            'ht_mode': 'HT40',
            'radio_band': '5g',
        },
        {
            'channel_A': 104,
            'channel_B': 136,
            'ht_mode': 'HT80',
            'radio_band': '5g',
        },
    ],
    "wm2_pre_cac_ht_mode_change_validation": [
        {
            'channel': 52,
            'ht_mode_a': 'HT80',
            'ht_mode_b': 'HT40',
            'radio_band': '5g',
        },
        {
            'channel': 44,
            'ht_mode_a': 'HT80',
            'ht_mode_b': 'HT80',
            'radio_band': '5g',
        },
        {
            'channel': 100,
            'ht_mode_a': 'HT80',
            'ht_mode_b': 'HT40',
            'radio_band': '5g',
        },
        {
            'channel': 136,
            'ht_mode_a': 'HT80',
            'ht_mode_b': 'HT40',
            'radio_band': '5g',
        },
    ],
    "wm2_ht_mode_and_channel_iteration": [
        # Configurations can be grouped into lists of several parameters, or specified individually
        {
            "channels": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
            ],
            "radio_band": "24g",
        },
        {
            "channels": [
                36,
                40,
                44,
                48,
                52,
                56,
                60,
                64,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
                "HT80",
            ],
            "radio_band": "5g",
        },
        {
            "channels": [
                101,
                105,
                109,
                113,
                117,
                121,
                125,
                129,
                133,
                137,
            ],
            "encryption": "WPA3",
            "ht_modes": [
                "HT20",
                "HT40",
                "HT80",
                "HT160",
            ],
            "radio_band": "6g",
        },
    ],
    "wm2_immutable_radio_freq_band": [
        {
            "channel": 6,
            "freq_band": "5G",
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "freq_band": "6G",
            "ht_mode": "HT20",
            "radio_band": "5g",
        },
        {
            "channel": 101,
            "encryption": "WPA3",
            "freq_band": "2.4G",
            "ht_mode": "HT20",
            "radio_band": "6g",
        },
    ],
    "wm2_immutable_radio_hw_mode": [
        {
            "channel": 1,
            "custom_hw_mode": "11b",
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "custom_hw_mode": "11n",
            "ht_mode": "HT20",
            "radio_band": "5g",
        },
        {
            "channel": 101,
            "custom_hw_mode": "11g",
            "encryption": "WPA3",
            "ht_mode": "HT20",
            "radio_band": "6g",
        },
    ],
    "wm2_immutable_radio_hw_type": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "hw_type": "bcm47189",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT20",
            "hw_type": "bcm47189",
            "radio_band": "5g",
        },
        {
            "channel": 101,
            "encryption": "WPA3",
            "ht_mode": "HT20",
            "hw_type": "bcm47189",
            "radio_band": "6g",
        },
    ],
    "wm2_leaf_ht_mode_change": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "custom_ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "custom_ht_mode": "HT80",
            "radio_band": "5g",
        },
        {
            "channel": 157,
            "ht_mode": "HT80",
            "custom_ht_mode": "HT40",
            "radio_band": "5g",
        },
        {
            "channel": 101,
            "encryption": "WPA3",
            "ht_mode": "HT80",
            "custom_ht_mode": "HT40",
            "radio_band": "6g",
        },
    ],
    "wm2_set_bcn_int": [
        {
            "bcn_int": 200,
            "channel": 1,
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "bcn_int": 400,
            "channel": 36,
            "ht_mode": "HT20",
            "radio_band": "5g",
        },
        {
            "bcn_int": 400,
            "channel": 52,
            "ht_mode": "HT20",
            "radio_band": "5g",
        },
        {
            "bcn_int": 600,
            "channel": 157,
            "ht_mode": "HT20",
            "radio_band": "5g",
        },
        {
            "bcn_int": 600,
            "channel": 101,
            "encryption": "WPA3",
            "ht_mode": "HT20",
            "radio_band": "6g",
        },
    ],
    "wm2_set_channel": [
        {
            "channels": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
            ],
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channels": [
                36,
                40,
                44,
                48,
                52,
                56,
                60,
                64,
                100,
                104,
                108,
                112,
                116,
            ],
            "ht_mode": "HT20",
            "radio_band": "5g",
        },
        {
            "channels": [
                101,
                105,
                109,
                113,
                117,
                121,
                125,
                129,
                133,
                137,
            ],
            "encryption": "WPA3",
            "ht_mode": "HT20",
            "radio_band": "6g",
        },
    ],
    "wm2_set_channel_neg": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "mismatch_channels": [
                36,
                101,
            ],
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT20",
            "mismatch_channels": [
                11,
                101,
            ],
            "radio_band": "5g",
        },
        {
            "channel": 101,
            "encryption": "WPA3",
            "ht_mode": "HT20",
            "mismatch_channels": [
                36,
                64,
            ],
            "radio_band": "6g",
        },
    ],
    "wm2_set_ht_mode": [
        {
            "channels": [
                1,
                6,
                11,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
            ],
            "radio_band": "24g",
        },
        {
            "channels": [
                36,
                44,
                56,
                64,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
                "HT80",
            ],
            "radio_band": "5g",
        },
        {
            "channels": [
                101,
                105,
                109,
                113,
            ],
            "encryption": "WPA3",
            "ht_modes": [
                "HT20",
                "HT40",
                "HT80",
                "HT160",
            ],
            "radio_band": "6g",
        },
    ],
    "wm2_set_ht_mode_neg": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "mismatch_ht_mode": "HT160",
            "radio_band": "24g",
        },
    ],
    "wm2_set_radio_country": [
        {
            "country": "US",
            "radio_band": "24g",
        },
        {
            "country": "US",
            "radio_band": "5g",
        },
        {
            "country": "US",
            "radio_band": "6g",
        },
    ],
    "wm2_set_radio_thermal_tx_chainmask": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channel": 52,
            "ht_mode": "HT80",
            "radio_band": "5g",
        },
        {
            "channel": 101,
            "encryption": "WPA3",
            "ht_mode": "HT20",
            "radio_band": "6g",
        },
    ],
    "wm2_set_radio_tx_chainmask": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT20",
            "radio_band": "5g",
        },
        {
            "channel": 101,
            "encryption": "WPA3",
            "ht_mode": "HT20",
            "radio_band": "6g",
        },
    ],
    "wm2_set_radio_tx_power": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "radio_band": "24g",
            "test_script_timeout": 5,
            "tx_powers": list(range(1, 30)),
        },
        {
            "channel": 36,
            "ht_mode": "HT20",
            "radio_band": "5g",
            "test_script_timeout": 5,
            "tx_powers": list(range(1, 30)),
        },
        {
            "channel": 101,
            "encryption": "WPA3",
            "ht_mode": "HT20",
            "radio_band": "6g",
            "test_script_timeout": 5,
            "tx_powers": list(range(1, 30)),
        },
    ],
    "wm2_set_radio_tx_power_neg": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "mismatch_tx_power": 32,
            "radio_band": "24g",
            "tx_power": 30,
        },
        {
            "channel": 36,
            "ht_mode": "HT20",
            "mismatch_tx_power": 32,
            "radio_band": "5g",
            "tx_power": 30,
        },
        {
            "channel": 101,
            "encryption": "WPA3",
            "ht_mode": "HT20",
            "mismatch_tx_power": 32,
            "radio_band": "6g",
            "tx_power": 30,
        },
    ],
    "wm2_set_radio_vif_configs": [
        {
            "channel": 1,
            "custom_channel": 6,
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "custom_channel": 48,
            "ht_mode": "HT20",
            "radio_band": "5g",
        },
        {
            "channel": 101,
            "custom_channel": 133,
            "encryption": "WPA3",
            "ht_mode": "HT20",
            "radio_band": "6g",
        },
    ],
    "wm2_set_ssid": [
        {
            "channel": 2,
            "ht_mode": "HT20",
            "radio_band": "24g",
            "ssids": [
                "plus+",
                "minus-",
                "asterisk*",
                "hash#",
                "question_mark?",
                "backslash\\",
                "emoji👍",
                "cyrilicГДИѲЛ",
                "arabic٤ټٽ",
                "hebrewאב",
                "japanese飾り羽",
                "special[\\T/]",
                "ssid with spaces",
                "a",
                "ssidsbetweenoneandthirtytwobytes",
            ],
        },
        {
            "channel": 36,
            "ht_mode": "HT20",
            "radio_band": "5g",
            "ssids": [
                "plus+",
                "minus-",
                "asterisk*",
                "hash#",
                "question_mark?",
                "backslash\\",
                "emoji👍",
                "cyrilicГДИѲЛ",
                "arabic٤ټٽ",
                "hebrewאב",
                "japanese飾り羽",
                "special[\\T/]",
                "ssid with spaces",
                "a",
                "ssidsbetweenoneandthirtytwobytes",
            ],
        },
        {
            "channel": 101,
            "encryption": "WPA3",
            "ht_mode": "HT20",
            "radio_band": "6g",
            "ssids": [
                "plus+",
                "minus-",
                "asterisk*",
                "hash#",
                "question_mark?",
                "backslash\\",
                "emoji👍",
                "cyrilicГДИѲЛ",
                "arabic٤ټٽ",
                "hebrewאב",
                "japanese飾り羽",
                "special[\\T/]",
                "ssid with spaces",
                "a",
                "ssidsbetweenoneandthirtytwobytes",
            ],
        },
    ],
    "wm2_set_wifi_credential_config": [
        {},
    ],
    "wm2_topology_change_change_parent_change_band_change_channel": [
        {
            "gw_channel": 1,
            "gw_radio_band": "24g",
            "ht_mode": "HT20",
            "leaf_channel": 36,
            "leaf_radio_band": "5g",
        },
        {
            "encryption": "WPA3",
            "gw_channel": 1,
            "gw_radio_band": "5g",
            "ht_mode": "HT20",
            "leaf_channel": 157,
            "leaf_radio_band": "6g",
        },
        {
            "encryption": "WPA3",
            "gw_channel": 157,
            "gw_radio_band": "6g",
            "ht_mode": "HT40",
            "leaf_channel": 1,
            "leaf_radio_band": "24g",
        },
    ],
    "wm2_topology_change_change_parent_same_band_change_channel": [
        {
            "gw_channel": 1,
            "ht_mode": "HT20",
            "leaf_channel": 4,
            "radio_band": "24g",
        },
        {
            "gw_channel": 36,
            "ht_mode": "HT40",
            "leaf_channel": 44,
            "radio_band": "5g",
        },
        {
            "encryption": "WPA3",
            "gw_channel": 101,
            "ht_mode": "HT40",
            "leaf_channel": 153,
            "radio_band": "6g",
        },
    ],
    "wm2_topology_change_change_parent_same_band_same_channel": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5g",
        },
        {
            "channel": 101,
            "encryption": "WPA3",
            "ht_mode": "HT40",
            "radio_band": "6g",
        },
    ],
    "wm2_validate_radio_mac_address": [
        {
            "radio_band": "24g",
        },
        {
            "radio_band": "5g",
        },
        {
            "radio_band": "6g",
        },
    ],
    "wm2_verify_associated_clients": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5g",
        },
        {
            "channel": 101,
            "encryption": "WPA3",
            "ht_mode": "HT20",
            "radio_band": "6g",
        },
    ],
    "wm2_verify_sta_send_csa": [
        {
            "channel": 1,
            "csa_channel": 6,
            "encryption": "WPA3",
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "csa_channel": 48,
            "encryption": "WPA3",
            "radio_band": "5g",
            "ht_mode": "HT40",
        },
        {
            "channel": 52,
            "csa_channel": 60,
            "encryption": "WPA3",
            "radio_band": "5g",
            "ht_mode": "HT40",
        },
        {
            "channel": 101,
            "csa_channel": 109,
            "encryption": "WPA3",
            "radio_band": "6g",
            "ht_mode": "HT40",
        },
        {
            "channel": 137,
            "csa_channel": 157,
            "encryption": "WPA3",
            "radio_band": "6g",
            "ht_mode": "HT40",
        },
    ],
    "wm2_verify_wifi_security_modes": [
        {
            "channel": 6,
            "encryption_list": [
                "open",
                "WPA2",
                "WPA3",
                "WPA3-transition",
            ],
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "encryption_list": [
                "open",
                "WPA2",
                "WPA3",
                "WPA3-transition",
            ],
            "ht_mode": "HT40",
            "radio_band": "5g",
        },
        {
            "channel": 157,
            "encryption_list": [
                "WPA3",
                "WPA3-transition",
            ],
            "ht_mode": "HT40",
            "radio_band": "6g",
        },
    ],
    "wm2_wifi_security_mix_on_multiple_aps": [
        {
            "channel": 6,
            "encryption_list": [
                "WPA2",
                "WPA3",
                "open",
            ],
            "ht_mode": "HT20",
            "radio_band": "24g",
            "vif_config": {
                "backhaul_ap": ["b-ap-24", 1],
                "home_ap": ["home-ap-24", 2],
                "onboard_ap": ["onboard-ap-24", 3],
                "auxillary_ap_1": ["aux-ap-124", 4],
                "auxillary_ap_2": ["aux-ap-224", 5],
                "fronthaul_ap": ["fhaul-ap-24", 6],
                "captive_portal": ["cportal-ap-24", 7],
            },
        },
        {
            "channel": 44,
            "encryption_list": [
                "WPA2",
                "WPA3",
                "open",
            ],
            "ht_mode": "HT20",
            "radio_band": "5g",
            "vif_config": {
                "backhaul_ap": ["b-ap-50", 1],
                "home_ap": ["home-ap-50", 2],
                "onboard_ap": ["onboard-ap-50", 3],
                "auxillary_ap_1": ["aux-ap-150", 4],
                "auxillary_ap_2": ["aux-ap-250", 5],
                "fronthaul_ap": ["fhaul-ap-50", 6],
                "captive_portal": ["cportal-ap-50", 7],
            },
        },
        {
            "channel": 101,
            "encryption_list": [
                "WPA3",
            ],
            "ht_mode": "HT20",
            "radio_band": "6g",
            "vif_config": {
                "backhaul_ap": ["b-ap-60", 1],
                "home_ap": ["home-ap-60", 2],
                "onboard_ap": ["onboard-ap-60", 3],
                "auxillary_ap_1": ["aux-ap-160", 4],
                "auxillary_ap_2": ["aux-ap-260", 5],
                "fronthaul_ap": ["fhaul-ap-60", 6],
                "captive_portal": ["cportal-ap-60", 7],
            },
        },
    ],
}
