debian_client:
  recommended: null
  legacy: null
  public: '3.1.10'
debian_server:
  recommended: '3.0.25'
  legacy: '3.0.25'
  public: '3.1.10'
linux_client:
  recommended: '1.2.29'
  legacy: '1.2.28'
  public: null
rpi_client:
  recommended: 'v2.0-178'
  legacy: 'v2.0-175'
  public: 'v2.1-10'
rpi_server:
  recommended: 'v2.0-187'
  legacy: 'v2.0-182'
  public: 'v2.1-10'
