test_cfg = {
    "wm2_check_wifi_credential_config": [
        {},
    ],
    "wm2_connect_wpa3_client": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 11,
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT20",
            "radio_band": "5gl",
        },
        {
            "channel": 48,
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "channel": 149,
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
        {
            "channel": 157,
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_connect_wpa3_leaf": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 11,
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "channel": 48,
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "channel": 149,
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
        {
            "channel": 157,
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_create_all_aps_per_radio": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
            "vif_config": {
                "backhaul_ap": ["wl1.1", 1],
                "home_ap": ["wl1.2", 2],
                "onboard_ap": ["wl1.3", 3],
                "auxillary_ap_1": ["wl1.4", 4],
                "auxillary_ap_2": ["wl1.5", 5],
                "fronthaul_ap": ["wl1.6", 6],
                "captive_portal": ["wl1.7", 7],
            },
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5gl",
            "vif_config": {
                "backhaul_ap": ["wl0.1", 1],
                "home_ap": ["wl0.2", 2],
                "onboard_ap": ["wl0.3", 3],
                "auxillary_ap_1": ["wl0.4", 4],
                "auxillary_ap_2": ["wl0.5", 5],
                "fronthaul_ap": ["wl0.6", 6],
                "captive_portal": ["wl0.7", 7],
            },
        },
        {
            "channel": 149,
            "ht_mode": "HT40",
            "radio_band": "5gu",
            "vif_config": {
                "backhaul_ap": ["wl2.1", 1],
                "home_ap": ["wl2.2", 2],
                "onboard_ap": ["wl2.3", 3],
                "auxillary_ap_1": ["wl2.4", 4],
                "auxillary_ap_2": ["wl2.5", 5],
                "fronthaul_ap": ["wl2.6", 6],
                "captive_portal": ["wl2.7", 7],
            },
        },
    ],
    "wm2_create_wpa3_ap": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "interface_type": "home_ap",
            "radio_band": "24g",
        },
        {
            "channel": 11,
            "ht_mode": "HT40",
            "interface_type": "backhaul_ap",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "interface_type": "home_ap",
            "radio_band": "5gl",
        },
        {
            "channel": 48,
            "ht_mode": "HT40",
            "interface_type": "backhaul_ap",
            "radio_band": "5gl",
        },
        {
            "channel": 149,
            "ht_mode": "HT40",
            "interface_type": "home_ap",
            "radio_band": "5gu",
        },
        {
            "channel": 157,
            "ht_mode": "HT20",
            "interface_type": "backhaul_ap",
            "radio_band": "5gu",
        },
    ],
    "wm2_dfs_cac_aborted": [
        {
            "channel_A": 52,
            "channel_B": 64,
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "channel_A": 100,
            "channel_B": 112,
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
        {
            "channel_A": 136,
            "channel_B": 144,
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_ht_mode_and_channel_iteration": [
        # Configurations can be grouped into lists of several parameters, or specified individually
        {
            "channels": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
            ],
            "radio_band": "24g",
        },
        {
            "channels": [
                36,
                40,
                44,
                48,
                52,
                56,
                60,
                64,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
                "HT80",
            ],
            "radio_band": "5gl",
        },
        {
            "channels": [
                100,
                104,
                108,
                112,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
                "HT80",
            ],
            "radio_band": "5gu",
        },
        {
            "channels": [
                116,
                120,
                124,
                128,
                132,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
                "HT80",
            ],
            "radio_band": "5gu",
        },
        {
            "channels": [
                136,
                140,
                144,
                149,
                153,
                157,
                161,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
                "HT80",
            ],
            "radio_band": "5gu",
        },
        {
            "channels": [
                165,
            ],
            "ht_modes": [
                "HT20",
            ],
            "radio_band": "5gu",
        },
    ],
    "wm2_immutable_radio_freq_band": [
        {
            "channel": 6,
            "freq_band": "5GL",
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "freq_band": "5GU",
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "channel": 149,
            "freq_band": "2.4G",
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_immutable_radio_hw_mode": [
        {
            "channel": 6,
            "custom_hw_mode": "11b",
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "custom_hw_mode": "11n",
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "channel": 149,
            "custom_hw_mode": "11g",
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_immutable_radio_hw_type": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "hw_type": "qca4219",
            "ignore_collect": True,
            "ignore_collect_msg": "FAIL: Testcase fails",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT20",
            "hw_type": "qca4220",
            "ignore_collect": True,
            "ignore_collect_msg": "FAIL: Testcase fails",
            "radio_band": "5gl",
        },
        {
            "channel": 157,
            "ht_mode": "HT20",
            "hw_type": "qca4221",
            "ignore_collect": True,
            "ignore_collect_msg": "FAIL: Testcase fails",
            "radio_band": "5gu",
        },
    ],
    "wm2_leaf_ht_mode_change": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "custom_ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "custom_ht_mode": "HT80",
            "radio_band": "5gl",
        },
        {
            "channel": 149,
            "ht_mode": "HT80",
            "custom_ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_pre_cac_channel_change_validation": [
        {
            'channel_A': 52,
            'channel_B': 60,
            'ht_mode': 'HT40',
            'radio_band': '5gl',
        },
        {
            'channel_A': 44,
            'channel_B': 56,
            'ht_mode': 'HT80',
            'radio_band': '5gl',
        },
        {
            'channel_A': 40,
            'channel_B': 60,
            'ht_mode': 'HT80',
            'radio_band': '5gl',
        },
        {
            'channel_A': 100,
            'channel_B': 108,
            'ht_mode': 'HT40',
            'radio_band': '5gu',
        },
        {
            'channel_A': 104,
            'channel_B': 136,
            'ht_mode': 'HT80',
            'radio_band': '5gu',
        },
    ],
    "wm2_pre_cac_ht_mode_change_validation": [
        {
            'channel': 52,
            'ht_mode_a': 'HT80',
            'ht_mode_b': 'HT40',
            'radio_band': '5gl',
        },
        {
            'channel': 44,
            'ht_mode_a': 'HT80',
            'ht_mode_b': 'HT80',
            'radio_band': '5gl',
        },
        {
            'channel': 100,
            'ht_mode_a': 'HT80',
            'ht_mode_b': 'HT40',
            'radio_band': '5gu',
        },
        {
            'channel': 136,
            'ht_mode_a': 'HT80',
            'ht_mode_b': 'HT40',
            'radio_band': '5gu',
        },
    ],
    "wm2_set_bcn_int": [
        {
            "bcn_int": 200,
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "bcn_int": 200,
            "channel": 11,
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "bcn_int": 400,
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "bcn_int": 400,
            "channel": 48,
            "ht_mode": "HT20",
            "radio_band": "5gl",
        },
        {
            "bcn_int": 600,
            "channel": 149,
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
        {
            "bcn_int": 600,
            "channel": 157,
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_set_channel": [
        {
            "channels": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
            ],
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channels": [
                36,
                40,
                44,
                48,
                52,
                56,
                60,
                64,
            ],
            "ht_mode": "HT20",
            "radio_band": "5gl",
        },
        {
            "channels": [
                100,
                104,
                108,
                112,
                116,
                120,
                124,
                128,
                132,
                136,
                140,
                144,
                149,
                153,
                157,
                161,
                165,
            ],
            "ht_mode": "HT20",
            "radio_band": "5gu",
        },
    ],
    "wm2_set_channel_neg": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "mismatch_channels": [
                36,
                123,
            ],
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT20",
            "mismatch_channels": [
                11,
                134,
            ],
            "radio_band": "5gl",
        },
        {
            "channel": 108,
            "ht_mode": "HT20",
            "mismatch_channels": [
                64,
                180,
            ],
            "radio_band": "5gu",
        },
    ],
    "wm2_set_ht_mode": [
        {
            "channels": [
                1,
                6,
                11,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
            ],
            "radio_band": "24g",
        },
        {
            "channels": [
                36,
                44,
                56,
                64,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
                "HT80",
            ],
            "radio_band": "5gl",
        },
        {
            "channels": [
                100,
                108,
                149,
                157,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
                "HT80",
            ],
            "radio_band": "5gu",
        },
    ],
    "wm2_set_ht_mode_neg": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "mismatch_ht_mode": "HT160",
            "radio_band": "24g",
        },
        {
            "channel": 157,
            "ht_mode": "HT20",
            "mismatch_ht_mode": "HT160",
            "radio_band": "5gu",
        },
    ],
    "wm2_set_radio_country": [
        {
            "country": "US",
            "radio_band": "24g",
        },
        {
            "country": "US",
            "radio_band": "5gl",
        },
        {
            "country": "US",
            "radio_band": "5gu",
        },
    ],
    "wm2_set_radio_thermal_tx_chainmask": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "channel": 149,
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_set_radio_tx_chainmask": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "channel": 149,
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_set_radio_tx_power": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
            "test_script_timeout": 5,
            "tx_powers": list(range(1, 30)),
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5gl",
            "test_script_timeout": 5,
            "tx_powers": list(range(1, 30)),
        },
        {
            "channel": 149,
            "ht_mode": "HT40",
            "radio_band": "5gu",
            "test_script_timeout": 5,
            "tx_powers": list(range(1, 30)),
        },
    ],
    "wm2_set_radio_tx_power_neg": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "mismatch_tx_power": 32,
            "radio_band": "24g",
            "tx_power": 30,
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "mismatch_tx_power": 32,
            "radio_band": "5gl",
            "tx_power": 30,
        },
        {
            "channel": 149,
            "ht_mode": "HT40",
            "mismatch_tx_power": 32,
            "radio_band": "5gu",
            "tx_power": 30,
        },
    ],
    "wm2_set_radio_vif_configs": [
        {
            "channel": 6,
            "custom_channel": 11,
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "custom_channel": 48,
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "channel": 149,
            "custom_channel": 157,
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_set_ssid": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
            "ssids": [
                "plus+",
                "minus-",
                "asterisk*",
                "hash#",
                "question_mark?",
                "backslash\\",
                "emoji👍",
                "cyrilicГДИѲЛ",
                "arabic٤ټٽ",
                "hebrewאב",
                "japanese飾り羽",
                "special[\\T/]",
                "ssid with spaces",
                "a",
                "ssidsbetweenoneandthirtytwobytes",
            ],
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5gl",
            "ssids": [
                "plus+",
                "minus-",
                "asterisk*",
                "hash#",
                "question_mark?",
                "backslash\\",
                "emoji👍",
                "cyrilicГДИѲЛ",
                "arabic٤ټٽ",
                "hebrewאב",
                "japanese飾り羽",
                "special[\\T/]",
                "ssid with spaces",
                "a",
                "ssidsbetweenoneandthirtytwobytes",
            ],
        },
        {
            "channel": 149,
            "ht_mode": "HT40",
            "radio_band": "5gu",
            "ssids": [
                "plus+",
                "minus-",
                "asterisk*",
                "hash#",
                "question_mark?",
                "backslash\\",
                "emoji👍",
                "cyrilicГДИѲЛ",
                "arabic٤ټٽ",
                "hebrewאב",
                "japanese飾り羽",
                "special[\\T/]",
                "ssid with spaces",
                "a",
                "ssidsbetweenoneandthirtytwobytes",
            ],
        },
    ],
    "wm2_set_wifi_credential_config": [
        {},
    ],
    "wm2_topology_change_change_parent_change_band_change_channel": [
        {
            "gw_channel": 6,
            "gw_radio_band": "24g",
            "ht_mode": "HT40",
            "leaf_channel": 48,
            "leaf_radio_band": "5gl",
        },
        {
            "gw_channel": 6,
            "gw_radio_band": "24g",
            "ht_mode": "HT40",
            "leaf_channel": 149,
            "leaf_radio_band": "5gu",
        },
        {
            "gw_channel": 48,
            "gw_radio_band": "5gl",
            "ht_mode": "HT40",
            "leaf_channel": 149,
            "leaf_radio_band": "5gu",
        },
    ],
    "wm2_topology_change_change_parent_same_band_change_channel": [
        {
            "gw_channel": 6,
            "ht_mode": "HT40",
            "leaf_channel": 11,
            "radio_band": "24g",
        },
        {
            "gw_channel": 36,
            "ht_mode": "HT40",
            "leaf_channel": 48,
            "radio_band": "5gl",
        },
        {
            "gw_channel": 149,
            "ht_mode": "HT40",
            "leaf_channel": 157,
            "radio_band": "5gu",
        },
    ],
    "wm2_topology_change_change_parent_same_band_same_channel": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "channel": 149,
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_validate_radio_mac_address": [
        {
            "radio_band": "24g",
        },
        {
            "radio_band": "5gl",
        },
        {
            "radio_band": "5gu",
        },
    ],
    "wm2_verify_associated_clients": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "channel": 157,
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_verify_sta_send_csa": [
        {
            "channel": 1,
            "csa_channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "csa_channel": 48,
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "channel": 149,
            "csa_channel": 157,
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_verify_wifi_security_modes": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
            "encryption_list": [
                "open",
                "WPA2",
                "WPA3",
                "WPA3-transition",
            ],
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5gl",
            "encryption_list": [
                "open",
                "WPA2",
                "WPA3",
                "WPA3-transition",
            ],
        },
        {
            "channel": 149,
            "ht_mode": "HT40",
            "radio_band": "5gu",
            "encryption_list": [
                "open",
                "WPA2",
                "WPA3",
                "WPA3-transition",
            ],
        },
    ],
    "wm2_wifi_security_mix_on_multiple_aps": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
            "encryption_list": [
                "WPA2",
                "WPA3",
                "open",
            ],
            "vif_config": {
                "backhaul_ap": ["wl1.1", 1],
                "home_ap": ["wl1.2", 2],
                "onboard_ap": ["wl1.3", 3],
                "auxillary_ap_1": ["wl1.4", 4],
                "auxillary_ap_2": ["wl1.5", 5],
                "fronthaul_ap": ["wl1.6", 6],
                "captive_portal": ["wl1.7", 7],
            },
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5gl",
            "encryption_list": [
                "WPA2",
                "WPA3",
                "open",
            ],
            "vif_config": {
                "backhaul_ap": ["wl0.1", 1],
                "home_ap": ["wl0.2", 2],
                "onboard_ap": ["wl0.3", 3],
                "auxillary_ap_1": ["wl0.4", 4],
                "auxillary_ap_2": ["wl0.5", 5],
                "fronthaul_ap": ["wl0.6", 6],
                "captive_portal": ["wl0.7", 7],
            },
        },
        {
            "channel": 149,
            "ht_mode": "HT40",
            "radio_band": "5gu",
            "encryption_list": [
                "WPA2",
                "WPA3",
                "open",
            ],
            "vif_config": {
                "backhaul_ap": ["wl2.1", 1],
                "home_ap": ["wl2.2", 2],
                "onboard_ap": ["wl2.3", 3],
                "auxillary_ap_1": ["wl2.4", 4],
                "auxillary_ap_2": ["wl2.5", 5],
                "fronthaul_ap": ["wl2.6", 6],
                "captive_portal": ["wl2.7", 7],
            },
        },
    ],
}
