ARG PARENT_IMAGE=""
FROM $PARENT_IMAGE:latest

# -- Install Pipfile dependencies:
RUN pip3 install \
 cryptography=="3.3.2" \
 butterfly=="3.2.5" \
 "butterfly[systemd]"=="3.2.5" \
 "butterfly[themes]"=="3.2.5" \
 flask-cors=="3.0.10" \
 paramiko=="2.7.2" \
 pytest-cov=="3.0.0" \
 pytest-dependency=="0.5.1" \
 pytest-ordering=="0.6" \
 filelock=="3.2" \
 google=="3.0.0"

RUN pip3 install pytest-select=="0.1.2"
