FUT_PASS_EXIT_CODE = 0

# Defaults for Device configuration
FUT_DEFAULT_DUT_DEVICE_MODE_OF_OPERATION = "router"

# Defaults for MQTT configuration and usage
FUT_DEFAULT_LOCATION_ID = "FUT_DEFAULT_LOCATION_ID"
FUT_DEFAULT_NODE_ID = "FUT_DEFAULT_NODE_ID"
FUT_DEFAULT_MQTT_TOPIC = "FUT_DEFAULT_MQTT_TOPIC"

# Defaults for AP creation
FUT_DEFAULT_AP_BRIDGE = True
FUT_DEFAULT_AP_BROADCAST_N = "255"
FUT_DEFAULT_AP_CHANNEL_MODE = "manual"
FUT_DEFAULT_AP_ENABLED = "true"
FUT_DEFAULT_AP_ENCRYPTION = "WPA2"
FUT_DEFAULT_AP_INET_ADDR_N = "130"
FUT_DEFAULT_AP_INTERFACE_TYPE = "home_ap"
FUT_DEFAULT_AP_IP_ASSIGN_SCHEME = "static"
FUT_DEFAULT_AP_MODE = "ap"
FUT_DEFAULT_AP_NAT = "false"
FUT_DEFAULT_AP_NETMASK = "255.255.255.128"
FUT_DEFAULT_AP_PSK = "FutDefaultApPsk"
FUT_DEFAULT_AP_SKIP_INET_CREATION = False
FUT_DEFAULT_AP_SSID_BROADCAST = "enabled"
FUT_DEFAULT_AP_SSID_PREFIX = "FUT_AP_SSID_"
FUT_DEFAULT_AP_VIF_RESET_DURING_CONFIGURATION = True
FUT_DEFAULT_AP_WIFI_SECURITY_TYPE = "wpa"

# Defaults for GW - LEAF connection / GRE tunnel
FUT_DEFAULT_GW_BHAUL_BROADCAST_N = "255"
FUT_DEFAULT_GW_BHAUL_ENABLED = "true"
FUT_DEFAULT_GW_BHAUL_IF_TYPE = "vif"
FUT_DEFAULT_GW_BHAUL_INET_ADDR_N = "129"
FUT_DEFAULT_GW_BHAUL_INTERFACE_TYPE = "backhaul_ap"
FUT_DEFAULT_GW_BHAUL_IP_ASSIGN_SCHEME = "static"
FUT_DEFAULT_GW_BHAUL_MAC_LIST_TYPE = "whitelist"
FUT_DEFAULT_GW_BHAUL_MODE = "ap"
FUT_DEFAULT_GW_BHAUL_NAT = "false"
FUT_DEFAULT_GW_BHAUL_NETMASK = "255.255.255.128"
FUT_DEFAULT_GW_BHAUL_NETWORK = "true"
FUT_DEFAULT_GW_BHAUL_PSK = "FutDefaultBhaulPsk"
FUT_DEFAULT_GW_BHAUL_SSID_BROADCAST = "disabled"
FUT_DEFAULT_GW_BHAUL_SSID_PREFIX = "FUT_BHAUL_SSID_"
FUT_DEFAULT_LEAF_BHAUL_INTERFACE_TYPE = "backhaul_sta"
FUT_DEFAULT_LEAF_ONBOARD_TYPE = "gre"
