test_cfg = {
    "sm_dynamic_noise_floor": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "mqtt_timeout": 300,
            "mqtt_topic": "sm_dynamic_noise_floor",
            "radio_band": "24g",
            "sm_radio_type": "2.4G",
            "sm_report_type": "raw",
            "sm_reporting_count": 0,
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "on-chan",
            "stats_type": "survey",
            "noise_range_dbm": (-120, 0),
        },
        {
            "channel": 48,
            "ht_mode": "HT40",
            "mqtt_timeout": 300,
            "mqtt_topic": "sm_dynamic_noise_floor",
            "radio_band": "5g",
            "sm_radio_type": "5G",
            "sm_report_type": "raw",
            "sm_reporting_count": 0,
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "on-chan",
            "stats_type": "survey",
            "noise_range_dbm": (-120, 0),
        },
        {
            "channel": 149,
            "ht_mode": "HT40",
            "mqtt_timeout": 300,
            "mqtt_topic": "sm_dynamic_noise_floor",
            "radio_band": "6g",
            "sm_radio_type": "6G",
            "sm_report_type": "raw",
            "sm_reporting_count": 0,
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "on-chan",
            "stats_type": "survey",
            "noise_range_dbm": (-120, 0),
        },
    ],
    "sm_leaf_report": [
        {
            "channel": 6,
            "encryption": "WPA3",
            "ht_mode": "HT40",
            "mqtt_timeout": 300,
            "mqtt_topic": "sm_leaf_report",
            "radio_band": "24g",
            "sm_radio_type": "2.4G",
            "sm_report_type": "raw",
            "sm_reporting_count": 0,
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "on-chan",
            "stats_type": "client",
        },
        {
            "channel": 48,
            "encryption": "WPA3",
            "ht_mode": "HT40",
            "mqtt_timeout": 300,
            "mqtt_topic": "sm_leaf_report",
            "radio_band": "5g",
            "sm_radio_type": "5G",
            "sm_report_type": "raw",
            "sm_reporting_count": 0,
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "on-chan",
            "stats_type": "client",
        },
        {
            "channel": 149,
            "encryption": "WPA3",
            "ht_mode": "HT40",
            "mqtt_timeout": 300,
            "mqtt_topic": "sm_leaf_report",
            "radio_band": "6g",
            "sm_radio_type": "6G",
            "sm_report_type": "raw",
            "sm_reporting_count": 0,
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "on-chan",
            "stats_type": "client",
        },
    ],
    "sm_neighbor_report": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "mqtt_timeout": 300,
            "mqtt_topic": "sm_neighbor_report",
            "radio_band": "24g",
            "sm_channel": 6,
            "sm_radio_type": "2.4G",
            "sm_report_type": "raw",
            "sm_reporting_count": 0,
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "on-chan",
            "survey_stats_type": "survey",
            "neighbors_stats_type": "neighbor",
        },
        {
            "channel": 48,
            "ht_mode": "HT40",
            "mqtt_timeout": 300,
            "mqtt_topic": "sm_neighbor_report",
            "radio_band": "5g",
            "sm_channel": 48,
            "sm_radio_type": "5G",
            "sm_report_type": "raw",
            "sm_reporting_count": 0,
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "on-chan",
            "survey_stats_type": "survey",
            "neighbors_stats_type": "neighbor",
        },
        {
            "channel": 149,
            "encryption": "WPA3",
            "ht_mode": "HT40",
            "mqtt_timeout": 300,
            "mqtt_topic": "sm_neighbor_report",
            "radio_band": "6g",
            "sm_channel": 149,
            "sm_radio_type": "6G",
            "sm_report_type": "raw",
            "sm_reporting_count": 0,
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "on-chan",
            "survey_stats_type": "survey",
            "neighbors_stats_type": "neighbor",
        },
    ],
    "sm_survey_report": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "mqtt_timeout": 300,
            "mqtt_topic": "sm_survey_report",
            "radio_band": "24g",
            "sm_channels": [
                6,
            ],
            "sm_radio_type": "2.4G",
            "sm_report_type": "raw",
            "sm_reporting_count": 0,
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "on-chan",
            "stats_type": "survey",
        },
        {
            "channel": 6,
            "ht_mode": "HT40",
            "mqtt_timeout": 300,
            "mqtt_topic": "sm_survey_report",
            "radio_band": "24g",
            "sm_channels": [
                11,
            ],
            "sm_radio_type": "2.4G",
            "sm_report_type": "raw",
            "sm_reporting_count": 0,
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "off-chan",
            "stats_type": "survey",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "mqtt_timeout": 300,
            "mqtt_topic": "sm_survey_report",
            "radio_band": "5g",
            "sm_channels": [
                36,
            ],
            "sm_radio_type": "5G",
            "sm_report_type": "raw",
            "sm_reporting_count": 0,
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "on-chan",
            "stats_type": "survey",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "mqtt_timeout": 300,
            "mqtt_topic": "sm_survey_report",
            "radio_band": "5g",
            "sm_channels": [
                48,
            ],
            "sm_radio_type": "5G",
            "sm_report_type": "raw",
            "sm_reporting_count": 0,
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "off-chan",
            "stats_type": "survey",
        },
        {
            "channel": 1,
            "encryption": "WPA3",
            "ht_mode": "HT40",
            "mqtt_timeout": 300,
            "mqtt_topic": "sm_survey_report",
            "radio_band": "6g",
            "sm_channels": [
                1,
            ],
            "sm_radio_type": "6G",
            "sm_report_type": "raw",
            "sm_reporting_count": 0,
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "on-chan",
            "stats_type": "survey",
        },
        {
            "channel": 1,
            "encryption": "WPA3",
            "ht_mode": "HT40",
            "mqtt_timeout": 300,
            "mqtt_topic": "sm_survey_report",
            "radio_band": "6g",
            "sm_channels": [
                101,
            ],
            "sm_radio_type": "6G",
            "sm_report_type": "raw",
            "sm_reporting_count": 0,
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "off-chan",
            "stats_type": "survey",
        },
    ],
}
