test_cfg = {
    "wm2_check_wifi_credential_config": [
        {},
    ],
    "wm2_connect_wpa3_client": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "ignore_collect": True,
            "ignore_collect_msg": "NOT APPLICABLE: Testcase only applicable for WiFi6 capable devices",
            "radio_band": "24g",
        },
    ],
    "wm2_connect_wpa3_leaf": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "ignore_collect": True,
            "ignore_collect_msg": "NOT APPLICABLE: Testcase only applicable for WiFi6 capable devices",
            "radio_band": "24g",
        },
    ],
    "wm2_create_all_aps_per_radio": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
            "vif_config": {
                "backhaul_ap": ["bhaul-ap-24", 1],
                "home_ap": ["home-ap-24", 2],
                "onboard_ap": ["onboard-ap-24", 3],
                "auxillary_ap_1": ["aux-ap-124", 4],
                "auxillary_ap_2": ["aux-ap-224", 5],
                "fronthaul_ap": ["fhaul-ap-24", 6],
                "captive_portal": ["cportal-ap-24", 7],
            },
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5gl",
            "vif_config": {
                "backhaul_ap": ["bhaul-ap-l50", 1],
                "home_ap": ["home-ap-l50", 2],
                "onboard_ap": ["onboard-ap-l50", 3],
                "auxillary_ap_1": ["aux-ap-150", 4],
                "auxillary_ap_2": ["aux-ap-250", 5],
                "fronthaul_ap": ["fhaul-ap-l50", 6],
                "captive_portal": ["cportal-ap-l50", 7],
            },
        },
        {
            "channel": 157,
            "ht_mode": "HT40",
            "radio_band": "5gu",
            "vif_config": {
                "backhaul_ap": ["bhaul-ap-u50", 1],
                "home_ap": ["home-ap-u50", 2],
                "onboard_ap": ["onboard-ap-u50", 3],
                "auxillary_ap_1": ["aux-ap-151", 4],
                "auxillary_ap_2": ["aux-ap-251", 5],
                "fronthaul_ap": ["fhaul-ap-u50", 6],
                "captive_portal": ["cportal-ap-u50", 7],
            },
        },
    ],
    "wm2_create_wpa3_ap": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "interface_type": "home_ap",
            "ignore_collect": True,
            "ignore_collect_msg": "NOT APPLICABLE: Testcase only applicable for WiFi6 capable devices",
            "radio_band": "24g",
        },
    ],
    "wm2_ht_mode_and_channel_iteration": [
        # Configurations can be grouped into lists of several parameters, or specified individually
        {
            "channels": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
            ],
            "radio_band": "24g",
        },
        {
            "channels": [
                36,
                40,
                44,
                48,
                52,
                56,
                60,
                64,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
                "HT80",
            ],
            "radio_band": "5gl",
        },
        {
            "channels": [
                100,
                104,
                108,
                112,
                116,
                120,
                124,
                128,
                132,
                136,
                149,
                153,
                157,
                161,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
                "HT80",
            ],
            "radio_band": "5gu",
        },
        {
            "channels": [
                140,
            ],
            "ht_modes": [
                "HT20",
            ],
            "radio_band": "5gu",
        },
        {
            "channels": [
                165,
            ],
            "ht_modes": [
                "HT20",
            ],
            "radio_band": "5gu",
        },
    ],
    "wm2_immutable_radio_freq_band": [
        {
            "channel": 1,
            "freq_band": "5GL",
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "freq_band": "5GU",
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "channel": 157,
            "freq_band": "2.4G",
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_immutable_radio_hw_mode": [
        {
            "channel": 1,
            "custom_hw_mode": "11b",
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "custom_hw_mode": "11n",
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "channel": 157,
            "custom_hw_mode": "11g",
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_immutable_radio_hw_type": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "hw_type": "qca4219",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "hw_type": "qca4220",
            "radio_band": "5gl",
        },
    ],
    "wm2_leaf_ht_mode_change": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "custom_ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "custom_ht_mode": "HT80",
            "radio_band": "5gl",
        },
        {
            "channel": 157,
            "ht_mode": "HT80",
            "custom_ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_pre_cac_channel_change_validation": [
        {
            'channel_A': 52,
            'channel_B': 60,
            'ht_mode': 'HT40',
            'radio_band': '5gl',
        },
        {
            'channel_A': 44,
            'channel_B': 56,
            'ht_mode': 'HT80',
            'radio_band': '5gl',
        },
        {
            'channel_A': 40,
            'channel_B': 60,
            'ht_mode': 'HT80',
            'radio_band': '5gl',
        },
        {
            'channel_A': 100,
            'channel_B': 108,
            'ht_mode': 'HT40',
            'radio_band': '5gu',
        },
        {
            'channel_A': 104,
            'channel_B': 136,
            'ht_mode': 'HT80',
            'radio_band': '5gu',
        },
    ],
    "wm2_pre_cac_ht_mode_change_validation": [
        {
            'channel': 52,
            'ht_mode_a': 'HT80',
            'ht_mode_b': 'HT40',
            'radio_band': '5gl',
        },
        {
            'channel': 44,
            'ht_mode_a': 'HT80',
            'ht_mode_b': 'HT80',
            'radio_band': '5gl',
        },
        {
            'channel': 100,
            'ht_mode_a': 'HT80',
            'ht_mode_b': 'HT40',
            'radio_band': '5gu',
        },
        {
            'channel': 136,
            'ht_mode_a': 'HT80',
            'ht_mode_b': 'HT40',
            'radio_band': '5gu',
        },
    ],
    "wm2_set_bcn_int": [
        {
            "bcn_int": 200,
            "channel": 1,
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "bcn_int": 400,
            "channel": 36,
            "ht_mode": "HT20",
            "radio_band": "5gl",
        },
        {
            "bcn_int": 400,
            "channel": 52,
            "ht_mode": "HT20",
            "radio_band": "5gl",
        },
        {
            "bcn_int": 600,
            "channel": 100,
            "ht_mode": "HT20",
            "radio_band": "5gu",
        },
        {
            "bcn_int": 600,
            "channel": 157,
            "ht_mode": "HT20",
            "radio_band": "5gu",
        },
    ],
    "wm2_set_channel": [
        {
            "channels": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
            ],
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channels": [
                36,
                40,
                44,
                48,
                52,
                56,
                60,
                64,
            ],
            "ht_mode": "HT20",
            "radio_band": "5gl",
        },
        {
            "channels": [
                100,
                104,
                108,
                112,
                116,
                120,
                124,
                128,
                132,
                136,
                140,
                149,
                153,
                157,
                161,
                165,
            ],
            "ht_mode": "HT20",
            "radio_band": "5gu",
        },
    ],
    "wm2_set_channel_neg": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "mismatch_channels": [
                36,
                123,
            ],
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT20",
            "mismatch_channels": [
                11,
                134,
            ],
            "radio_band": "5gl",
        },
        {
            "channel": 108,
            "ht_mode": "HT20",
            "mismatch_channels": [
                64,
                180,
            ],
            "radio_band": "5gu",
        },
    ],
    "wm2_set_ht_mode": [
        {
            "channels": [
                1,
                6,
                11,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
            ],
            "radio_band": "24g",
        },
        {
            "channels": [
                36,
                44,
                56,
                64,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
                "HT80",
            ],
            "radio_band": "5gl",
        },
        {
            "channels": [
                100,
                108,
                149,
                157,
            ],
            "ht_modes": [
                "HT20",
                "HT40",
                "HT80",
            ],
            "radio_band": "5gu",
            "channel_change_timeout": 120,
        },
    ],
    "wm2_set_ht_mode_neg": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "mismatch_ht_mode": "HT160",
            "radio_band": "24g",
        },
        {
            "channel": 149,
            "ht_mode": "HT20",
            "mismatch_ht_mode": "HT160",
            "radio_band": "5gu",
        },
    ],
    "wm2_set_radio_country": [
        {
            "country": "US",
            "radio_band": "24g",
        },
        {
            "country": "US",
            "radio_band": "5gl",
        },
        {
            "country": "US",
            "radio_band": "5gu",
        },
    ],
    "wm2_set_radio_thermal_tx_chainmask": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "ignore_collect": True,
            "ignore_collect_msg": "FAIL: Device does not support tx_chainmask",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT20",
            "ignore_collect": True,
            "ignore_collect_msg": "FAIL: Device does not support tx_chainmask",
            "radio_band": "5gl",
        },
        {
            "channel": 157,
            "ht_mode": "HT20",
            "ignore_collect": True,
            "ignore_collect_msg": "FAIL: Device does not support tx_chainmask",
            "radio_band": "5gu",
        },
    ],
    "wm2_set_radio_tx_chainmask": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT20",
            "radio_band": "5gl",
        },
        {
            "channel": 157,
            "ht_mode": "HT20",
            "radio_band": "5gu",
        },
    ],
    "wm2_set_radio_tx_power": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "radio_band": "24g",
            "test_script_timeout": 5,
            "tx_powers": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
            ],
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5gl",
            "test_script_timeout": 5,
            "tx_powers": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24,
            ],
        },
        {
            "channel": 157,
            "ht_mode": "HT40",
            "radio_band": "5gu",
            "test_script_timeout": 5,
            "tx_powers": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24,
            ],
        },
    ],
    "wm2_set_radio_tx_power_neg": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "mismatch_tx_power": 27,
            "radio_band": "24g",
            "tx_power": 23,
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "mismatch_tx_power": 27,
            "radio_band": "5gl",
            "tx_power": 23,
        },
        {
            "channel": 157,
            "ht_mode": "HT40",
            "mismatch_tx_power": 27,
            "radio_band": "5gu",
            "tx_power": 23,
        },
    ],
    "wm2_set_radio_vif_configs": [
        {
            "channel": 1,
            "custom_channel": 6,
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "custom_channel": 48,
            "ht_mode": "HT20",
            "radio_band": "5gl",
        },
        {
            "channel": 149,
            "custom_channel": 157,
            "ht_mode": "HT20",
            "radio_band": "5gu",
        },
    ],
    "wm2_set_ssid": [
        {
            "channel": 2,
            "ht_mode": "HT20",
            "radio_band": "24g",
            "ssids": [
                "plus+",
                "minus-",
                "asterisk*",
                "hash#",
                "question_mark?",
                "backslash\\",
                "emoji👍",
                "cyrilicГДИѲЛ",
                "arabic٤ټٽ",
                "hebrewאב",
                "japanese飾り羽",
                "special[\\T/]",
                "ssid with spaces",
                "a",
                "ssidsbetweenoneandthirtytwobytes",
            ],
        },
        {
            "channel": 36,
            "ht_mode": "HT20",
            "radio_band": "5gl",
            "ssids": [
                "plus+",
                "minus-",
                "asterisk*",
                "hash#",
                "question_mark?",
                "backslash\\",
                "emoji👍",
                "cyrilicГДИѲЛ",
                "arabic٤ټٽ",
                "hebrewאב",
                "japanese飾り羽",
                "special[\\T/]",
                "ssid with spaces",
                "a",
                "ssidsbetweenoneandthirtytwobytes",
            ],
        },
        {
            "channel": 157,
            "ht_mode": "HT20",
            "radio_band": "5gu",
            "ssids": [
                "plus+",
                "minus-",
                "asterisk*",
                "hash#",
                "question_mark?",
                "backslash\\",
                "emoji👍",
                "cyrilicГДИѲЛ",
                "arabic٤ټٽ",
                "hebrewאב",
                "japanese飾り羽",
                "special[\\T/]",
                "ssid with spaces",
                "a",
                "ssidsbetweenoneandthirtytwobytes",
            ],
        },
    ],
    "wm2_set_wifi_credential_config": [
        {},
    ],
    "wm2_topology_change_change_parent_change_band_change_channel": [
        {
            "gw_channel": 1,
            "gw_radio_band": "24g",
            "ht_mode": "HT20",
            "leaf_channel": 36,
            "leaf_radio_band": "5gl",
        },
        {
            "gw_channel": 1,
            "gw_radio_band": "24g",
            "ht_mode": "HT20",
            "leaf_channel": 100,
            "leaf_radio_band": "5gu",
        },
        {
            "gw_channel": 36,
            "gw_radio_band": "5gl",
            "ht_mode": "HT40",
            "leaf_channel": 100,
            "leaf_radio_band": "5gu",
        },
    ],
    "wm2_topology_change_change_parent_same_band_change_channel": [
        {
            "gw_channel": 1,
            "ht_mode": "HT20",
            "leaf_channel": 4,
            "radio_band": "24g",
        },
        {
            "gw_channel": 36,
            "ht_mode": "HT40",
            "leaf_channel": 44,
            "radio_band": "5gl",
        },
        {
            "gw_channel": 100,
            "ht_mode": "HT40",
            "ignore_collect": True,
            "ignore_collect_msg": "FAIL: Testcase fails",
            "leaf_channel": 157,
            "radio_band": "5gu",
        },
    ],
    "wm2_topology_change_change_parent_same_band_same_channel": [
        {
            "channel": 1,
            "ht_mode": "HT20",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "channel": 100,
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_validate_radio_mac_address": [
        {
            "radio_band": "24g",
        },
        {
            "radio_band": "5gl",
        },
        {
            "radio_band": "5gu",
        },
    ],
    "wm2_verify_associated_clients": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5gl",
        },
        {
            "channel": 157,
            "ht_mode": "HT40",
            "radio_band": "5gu",
        },
    ],
    "wm2_verify_sta_send_csa": [
        {
            "channel": 6,
            "csa_channel": 8,
            "encryption": "WPA2",
            "ht_mode": "HT20",
            "ignore_collect": True,
            "ignore_collect_msg": "FAIL: Testcase fails",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "csa_channel": 48,
            "encryption": "WPA2",
            "ht_mode": "HT40",
            "ignore_collect": True,
            "ignore_collect_msg": "FAIL: Testcase fails",
            "radio_band": "5gl",
        },
        {
            "channel": 52,
            "csa_channel": 60,
            "encryption": "WPA2",
            "ht_mode": "HT40",
            "ignore_collect": True,
            "ignore_collect_msg": "FAIL: Testcase fails",
            "radio_band": "5gl",
        },
        {
            "channel": 100,
            "csa_channel": 108,
            "encryption": "WPA2",
            "ht_mode": "HT40",
            "ignore_collect": True,
            "ignore_collect_msg": "FAIL: Testcase fails",
            "radio_band": "5gu",
        },
        {
            "channel": 149,
            "csa_channel": 157,
            "encryption": "WPA2",
            "ht_mode": "HT40",
            "ignore_collect": True,
            "ignore_collect_msg": "FAIL: Testcase fails",
            "radio_band": "5gu",
        },
    ],
    "wm2_verify_wifi_security_modes": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
            "encryption_list": [
                "open",
                "WPA2",
                "WPA3",
                "WPA3-transition",
            ],
        },
        {
            "channel": 52,
            "ht_mode": "HT40",
            "radio_band": "5gl",
            "encryption_list": [
                "open",
                "WPA2",
                "WPA3",
                "WPA3-transition",
            ],
        },
        {
            "channel": 157,
            "ht_mode": "HT40",
            "radio_band": "5gu",
            "encryption_list": [
                "open",
                "WPA2",
                "WPA3",
                "WPA3-transition",
            ],
        },
    ],
    "wm2_wifi_security_mix_on_multiple_aps": [
        {
            "channel": 6,
            "ht_mode": "HT40",
            "radio_band": "24g",
            "encryption_list": [
                "WPA2",
                "WPA3",
                "open",
            ],
            "vif_config": {
                "backhaul_ap": ["bhaul-ap-24", 1],
                "home_ap": ["home-ap-24", 2],
                "onboard_ap": ["onboard-ap-24", 3],
                "auxillary_ap_1": ["aux-ap-124", 4],
                "auxillary_ap_2": ["aux-ap-224", 5],
                "fronthaul_ap": ["fhaul-ap-24", 6],
                "captive_portal": ["cportal-ap-24", 7],
            },
        },
        {
            "channel": 36,
            "ht_mode": "HT40",
            "radio_band": "5gl",
            "encryption_list": [
                "WPA2",
                "WPA3",
                "open",
            ],
            "vif_config": {
                "backhaul_ap": ["bhaul-ap-l50", 1],
                "home_ap": ["home-ap-l50", 2],
                "onboard_ap": ["onboard-ap-l50", 3],
                "auxillary_ap_1": ["aux-ap-150", 4],
                "auxillary_ap_2": ["aux-ap-250", 5],
                "fronthaul_ap": ["fhaul-ap-l50", 6],
                "captive_portal": ["cportal-ap-l50", 7],
            },
        },
        {
            "channel": 157,
            "ht_mode": "HT40",
            "radio_band": "5gu",
            "encryption_list": [
                "WPA2",
                "WPA3",
                "open",
            ],
            "vif_config": {
                "backhaul_ap": ["bhaul-ap-u50", 1],
                "home_ap": ["home-ap-u50", 2],
                "onboard_ap": ["onboard-ap-u50", 3],
                "auxillary_ap_1": ["aux-ap-151", 4],
                "auxillary_ap_2": ["aux-ap-251", 5],
                "fronthaul_ap": ["fhaul-ap-u50", 6],
                "captive_portal": ["cportal-ap-u50", 7],
            },
        },
    ],
}
