test_cfg = {
    "fsm_configure_fsm_tables": [
        {
            "handler": "dev_dns",
            "plugin": "libfsm_dns.so",
            "tap_name_postfix": "tdns",
        },
        {
            "handler": "dev_http",
            "plugin": "libfsm_http.so",
            "tap_name_postfix": "thttp",
        },
        {
            "handler": "dev_ndp",
            "plugin": "libfsm_ndp.so",
            "tap_name_postfix": "tupnp",
        },
    ],
    "fsm_configure_openflow_rules": [
        {
            "action": "normal,output:3001",
            "rule": "udp,tp_dst=53",
            "token": "dev_flow_dns_out",
        },
        {
            "action": "normal,output:4001",
            "rule": "tcp,tcp_dst=80",
            "token": "dev_flow_http_out",
        },
        {
            "action": "output:5001",
            "rule": "udp,udp_dst=1900",
            "token": "dev_flow_upnp_out",
        },
    ],
    "fsm_configure_test_dns_plugin": [
        {
            "channel": 6,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_dns.so",
            "plugin_web_cat": "libfsm_wcnull.so",
            "radio_band": "24g",
            "url_block": "google.com",
            "url_redirect": "1.2.3.4",
        },
        {
            "channel": 11,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_dns.so",
            "plugin_web_cat": "libfsm_wcnull.so",
            "radio_band": "24g",
            "url_block": "google.com",
            "url_redirect": "1.2.3.4",
        },
        {
            "channel": 36,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_dns.so",
            "plugin_web_cat": "libfsm_wcnull.so",
            "radio_band": "5gl",
            "url_block": "google.com",
            "url_redirect": "1.2.3.4",
        },
        {
            "channel": 48,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_dns.so",
            "plugin_web_cat": "libfsm_wcnull.so",
            "radio_band": "5gl",
            "url_block": "google.com",
            "url_redirect": "1.2.3.4",
        },
        {
            "channel": 149,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_dns.so",
            "plugin_web_cat": "libfsm_wcnull.so",
            "radio_band": "5gu",
            "url_block": "google.com",
            "url_redirect": "1.2.3.4",
        },
        {
            "channel": 157,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_dns.so",
            "plugin_web_cat": "libfsm_wcnull.so",
            "radio_band": "5gu",
            "url_block": "google.com",
            "url_redirect": "1.2.3.4",
        },
    ],
    "fsm_configure_test_dpi_http_sni_request": [
        {
            "channel": 6,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin_dpi_sni": "libfsm_dpi_sni.so",
            "plugin_gk": "libfsm_gatekeeper.so",
            "radio_band": "24g",
            "url": "http://www.opensync.io",
            "verdict": "allowed",
        },
    ],
    "fsm_configure_test_dpi_http_url_request": [
        {
            "channel": 6,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin_dpi_sni": "libfsm_dpi_sni.so",
            "plugin_gk": "libfsm_gatekeeper.so",
            "radio_band": "24g",
            "url": "http://www.neverssl.com/changes",
            "verdict": "allowed",
        },
    ],
    "fsm_configure_test_http_plugin": [
        {
            "channel": 6,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_http.so",
            "radio_band": "24g",
            "user_agent": "fsm_http_user_agent",
        },
        {
            "channel": 11,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_http.so",
            "radio_band": "24g",
            "user_agent": "fsm_http_user_agent",
        },
        {
            "channel": 36,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_http.so",
            "radio_band": "5gl",
            "user_agent": "fsm_http_user_agent",
        },
        {
            "channel": 48,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_http.so",
            "radio_band": "5gl",
            "user_agent": "fsm_http_user_agent",
        },
        {
            "channel": 149,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_http.so",
            "radio_band": "5gu",
            "user_agent": "fsm_http_user_agent",
        },
        {
            "channel": 157,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_http.so",
            "radio_band": "5gu",
            "user_agent": "fsm_http_user_agent",
        },
    ],
    "fsm_configure_test_http_url_gatekeeper_verdict": [
        {
            "channel": 6,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin_dpi_sni": "libfsm_dpi_sni.so",
            "plugin_gk": "libfsm_gatekeeper.so",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin_dpi_sni": "libfsm_dpi_sni.so",
            "plugin_gk": "libfsm_gatekeeper.so",
            "radio_band": "5gl",
        },
        {
            "channel": 149,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin_dpi_sni": "libfsm_dpi_sni.so",
            "plugin_gk": "libfsm_gatekeeper.so",
            "radio_band": "5gu",
        },
    ],
    "fsm_configure_test_ndp_plugin": [
        {
            "channel": 6,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_ndp.so",
            "radio_band": "24g",
        },
        {
            "channel": 11,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_ndp.so",
            "radio_band": "24g",
        },
        {
            "channel": 36,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_ndp.so",
            "radio_band": "5gl",
        },
        {
            "channel": 48,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_ndp.so",
            "radio_band": "5gl",
        },
        {
            "channel": 149,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_ndp.so",
            "radio_band": "5gu",
        },
        {
            "channel": 157,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_ndp.so",
            "radio_band": "5gu",
        },
    ],
    "fsm_configure_test_upnp_plugin": [
        {
            "channel": 6,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_upnp.so",
            "radio_band": "24g",
            "upnp_device_type": "urn:plume-test:device:test:1",
            "upnp_friendly_name": "FUT test device",
            "upnp_manufacturer": "FUT testing, Inc",
            "upnp_manufacturer_URL": "https://www.fut.com",
            "upnp_model_description": "FUT UPnP service",
            "upnp_model_name": "FUT tester",
            "upnp_model_number": "1.0",
        },
        {
            "channel": 11,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_upnp.so",
            "radio_band": "24g",
            "upnp_device_type": "urn:plume-test:device:test:1",
            "upnp_friendly_name": "FUT test device",
            "upnp_manufacturer": "FUT testing, Inc",
            "upnp_manufacturer_URL": "https://www.fut.com",
            "upnp_model_description": "FUT UPnP service",
            "upnp_model_name": "FUT tester",
            "upnp_model_number": "1.0",
        },
        {
            "channel": 36,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_upnp.so",
            "radio_band": "5gl",
            "upnp_device_type": "urn:plume-test:device:test:1",
            "upnp_friendly_name": "FUT test device",
            "upnp_manufacturer": "FUT testing, Inc",
            "upnp_manufacturer_URL": "https://www.fut.com",
            "upnp_model_description": "FUT UPnP service",
            "upnp_model_name": "FUT tester",
            "upnp_model_number": "1.0",
        },
        {
            "channel": 48,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_upnp.so",
            "radio_band": "5gl",
            "upnp_device_type": "urn:plume-test:device:test:1",
            "upnp_friendly_name": "FUT test device",
            "upnp_manufacturer": "FUT testing, Inc",
            "upnp_manufacturer_URL": "https://www.fut.com",
            "upnp_model_description": "FUT UPnP service",
            "upnp_model_name": "FUT tester",
            "upnp_model_number": "1.0",
        },
        {
            "channel": 149,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_upnp.so",
            "radio_band": "5gu",
            "upnp_device_type": "urn:plume-test:device:test:1",
            "upnp_friendly_name": "FUT test device",
            "upnp_manufacturer": "FUT testing, Inc",
            "upnp_manufacturer_URL": "https://www.fut.com",
            "upnp_model_description": "FUT UPnP service",
            "upnp_model_name": "FUT tester",
            "upnp_model_number": "1.0",
        },
        {
            "channel": 157,
            "device_mode": "router",
            "ht_mode": "HT40",
            "plugin": "libfsm_upnp.so",
            "radio_band": "5gu",
            "upnp_device_type": "urn:plume-test:device:test:1",
            "upnp_friendly_name": "FUT test device",
            "upnp_manufacturer": "FUT testing, Inc",
            "upnp_manufacturer_URL": "https://www.fut.com",
            "upnp_model_description": "FUT UPnP service",
            "upnp_model_name": "FUT tester",
            "upnp_model_number": "1.0",
        },
        {
            "channel": 6,
            "device_mode": "bridge",
            "ht_mode": "HT40",
            "plugin": "libfsm_upnp.so",
            "radio_band": "24g",
            "upnp_device_type": "urn:plume-test:device:test:1",
            "upnp_friendly_name": "FUT test device",
            "upnp_manufacturer": "FUT testing, Inc",
            "upnp_manufacturer_URL": "https://www.fut.com",
            "upnp_model_description": "FUT UPnP service",
            "upnp_model_name": "FUT tester",
            "upnp_model_number": "1.0",
        },
        {
            "channel": 11,
            "device_mode": "bridge",
            "ht_mode": "HT40",
            "plugin": "libfsm_upnp.so",
            "radio_band": "24g",
            "upnp_device_type": "urn:plume-test:device:test:1",
            "upnp_friendly_name": "FUT test device",
            "upnp_manufacturer": "FUT testing, Inc",
            "upnp_manufacturer_URL": "https://www.fut.com",
            "upnp_model_description": "FUT UPnP service",
            "upnp_model_name": "FUT tester",
            "upnp_model_number": "1.0",
        },
        {
            "channel": 36,
            "device_mode": "bridge",
            "ht_mode": "HT40",
            "plugin": "libfsm_upnp.so",
            "radio_band": "5gl",
            "upnp_device_type": "urn:fut-test:device:test:1",
            "upnp_friendly_name": "FUT test device",
            "upnp_manufacturer": "FUT testing, Inc",
            "upnp_manufacturer_URL": "https://www.fut.com",
            "upnp_model_description": "FUT UPnP service",
            "upnp_model_name": "FUT tester",
            "upnp_model_number": "1.0",
        },
        {
            "channel": 48,
            "device_mode": "bridge",
            "ht_mode": "HT40",
            "plugin": "libfsm_upnp.so",
            "radio_band": "5gl",
            "upnp_device_type": "urn:plume-test:device:test:1",
            "upnp_friendly_name": "FUT test device",
            "upnp_manufacturer": "FUT testing, Inc",
            "upnp_manufacturer_URL": "https://www.fut.com",
            "upnp_model_description": "FUT UPnP service",
            "upnp_model_name": "FUT tester",
            "upnp_model_number": "1.0",
        },
        {
            "channel": 149,
            "device_mode": "bridge",
            "ht_mode": "HT40",
            "plugin": "libfsm_upnp.so",
            "radio_band": "5gu",
            "upnp_device_type": "urn:plume-test:device:test:1",
            "upnp_friendly_name": "FUT test device",
            "upnp_manufacturer": "FUT testing, Inc",
            "upnp_manufacturer_URL": "https://www.fut.com",
            "upnp_model_description": "FUT UPnP service",
            "upnp_model_name": "FUT tester",
            "upnp_model_number": "1.0",
        },
        {
            "channel": 157,
            "device_mode": "bridge",
            "ht_mode": "HT40",
            "plugin": "libfsm_upnp.so",
            "radio_band": "5gu",
            "upnp_device_type": "urn:plume-test:device:test:1",
            "upnp_friendly_name": "FUT test device",
            "upnp_manufacturer": "FUT testing, Inc",
            "upnp_manufacturer_URL": "https://www.fut.com",
            "upnp_model_description": "FUT UPnP service",
            "upnp_model_name": "FUT tester",
            "upnp_model_number": "1.0",
        },
    ],
    "fsm_configure_test_walleye_plugin": [
        {
            "plugin": "libfsm_walleye_dpi.so",
        },
    ],
    "fsm_create_tap_interface": [
        {
            "of_port": 3001,
            "tap_name_postfix": "tdns",
        },
        {
            "of_port": 4001,
            "tap_name_postfix": "thttp",
        },
        {
            "of_port": 5001,
            "tap_name_postfix": "tupnp",
        },
    ],
}
