test_cfg = {
    "nfm_native_ebtable_check": [
        {
            "chain_name": "BROUTING",
            "name": "drop_dest_mac",
            "priority": 1,
            "rule": '"-d 60:b4:f7:fc:2d:44"',
            "table_name": "broute",
            "target": "DROP",
            "update_target": "ACCEPT",
        },
        {
            "chain_name": "INPUT",
            "name": "allow_src_mac",
            "priority": 10,
            "rule": '"-s 10:24:1d:c9:a0:27"',
            "table_name": "filter",
            "target": "DROP",
            "update_target": "ACCEPT",
        },
        {
            "chain_name": "FORWARD",
            "name": "multicast_drop",
            "priority": 10,
            "rule": '"-d Multicast"',
            "table_name": "filter",
            "target": "DROP",
            "update_target": "ACCEPT",
        },
        {
            "chain_name": "OUTPUT",
            "name": "output_arp_drop",
            "priority": 10,
            "rule": '"-p ARP"',
            "table_name": "filter",
            "target": "DROP",
            "update_target": "ACCEPT",
        },
        {
            "chain_name": "PREROUTING",
            "name": "prerouting_drop",
            "priority": 10,
            "rule": '"-s 11:22:33:44:55:66"',
            "table_name": "nat",
            "target": "DROP",
            "update_target": "ACCEPT",
        },
        {
            "chain_name": "POSTROUTING",
            "name": "postrouting_drop",
            "priority": 10,
            "rule": '"-d 66:55:44:33:22:11"',
            "table_name": "nat",
            "target": "ACCEPT",
            "update_target": "DROP",
        },
        {
            "chain_name": "OUTPUT",
            "name": "output_drop",
            "priority": 10,
            "rule": '""',
            "table_name": "nat",
            "target": "DROP",
            "update_target": "CONTINUE",
        },
    ],
    "nfm_native_ebtable_template_check": [
        {
            "chain_name": "BROUTING",
            "name": "drop_dest_mac",
            "priority": 1,
            "table_name": "broute",
            "target": "DROP",
            "update_target": "ACCEPT",
        },
        {
            "chain_name": "INPUT",
            "name": "allow_src_mac",
            "priority": 10,
            "table_name": "filter",
            "target": "DROP",
            "update_target": "ACCEPT",
        },
        {
            "chain_name": "FORWARD",
            "name": "multicast_drop",
            "priority": 10,
            "table_name": "filter",
            "target": "DROP",
            "update_target": "ACCEPT",
        },
        {
            "chain_name": "OUTPUT",
            "name": "output_arp_drop",
            "priority": 10,
            "table_name": "filter",
            "target": "DROP",
            "update_target": "ACCEPT",
        },
        {
            "chain_name": "PREROUTING",
            "name": "prerouting_drop",
            "priority": 10,
            "table_name": "nat",
            "target": "DROP",
            "update_target": "ACCEPT",
        },
        {
            "chain_name": "POSTROUTING",
            "name": "postrouting_drop",
            "priority": 10,
            "table_name": "nat",
            "target": "ACCEPT",
            "update_target": "DROP",
        },
        {
            "chain_name": "OUTPUT",
            "name": "output_drop",
            "priority": 10,
            "table_name": "nat",
            "target": "DROP",
            "update_target": "ACCEPT",
        },
    ],
}
