fut_required_system_tools = [
    "break",
    "case",
    "cd",
    "curl",
    "do",
    "eval",
    "exit",
    "export",
    "for",
    "getopts",
    "hostapd",
    "hostapd_cli",
    "if",
    "ifconfig",
    "ip",
    "iptables",
    "miniupnpd",
    "ovsh",
    "ping",
    "ping6",
    "return",
    "scp",
    "set",
    "shift",
    "source",
    "ssh",
    "trap",
    "type",
    "while",
    "wpa_cli",
    "wpa_supplicant",
]
fut_required_busybox_builtins = [
    "[",
    "[[",
    "awk",
    "basename",
    "cat",
    "chmod",
    "cut",
    "date",
    "echo",
    "false",
    "find",
    "grep",
    "head",
    "kill",
    "killall",
    "ls",
    "mkdir",
    "pgrep",
    "pidof",
    "printf",
    "ps",
    "rm",
    "route",
    "sed",
    "seq",
    "sh",
    "sleep",
    "tail",
    "tar",
    "test",
    "touch",
    "tr",
    "true",
    "udhcpc",
    "wc",
    "which",
]
opensync_required_system_tools = [
    "dnsmasq",
    "hostapd_cli",
    "ip6tables-restore",
    "iptables-restore",
    "odhcp6c",
    "pppd",
    "read",
    "scp",
    "tcpdump",
    "wpa_cli",
    "wpa_supplicant",
]
opensync_required_busybox_builtins = [
    "arping",
    "ash",
    "base64",
    "cp",
    "dd",
    "devmem",
    "df",
    "dirname",
    "du",
    "egrep",
    "env",
    "expr",
    "free",
    "hexdump",
    "logger",
    "lspci",
    "md5sum",
    "mkfifo",
    "mktemp",
    "passwd",
    "pivot_root",
    "pwd",
    "reboot",
    "rmdir",
    "sort",
    "start-stop-daemon",
    "tee",
    "timeout",
    "umount",
    "uname",
    "uptime",
    "vconfig",
    "vi",
    "xargs",
    "yes",
]
busybox_builtins_only = [
    "cmp",
    "dmesg",
    "gzip",
    "halt",
    "ln",
    "mount",
    "mv",
    "nc",
    "netstat",
    "nslookup",
    "readlink",
    "sync",
    "wget",
]

test_inputs = {
    "brv_busybox_builtins": {
        "args_mapping": ["busybox_builtin"],
        "inputs": list(set(busybox_builtins_only + opensync_required_busybox_builtins + fut_required_busybox_builtins)),
    },
    "brv_is_script_on_system_fut": {
        "args_mapping": ["system_script"],
        "inputs": [
            "/etc/init.d/healthcheck",
            "/etc/init.d/opensync",
            "/etc/init.d/openvswitch",
            "/proc/net/vlan/config",
            "/sbin/udhcpc",
            "/tmp/resolv.conf",
            "/usr/opensync/etc/kconfig",
            "/var/etc/dnsmasq.conf",
        ],
    },
    "brv_is_tool_on_system_fut": {
        "args_mapping": ["system_tool"],
        "inputs": list(set(fut_required_system_tools + fut_required_busybox_builtins)),
    },
    "brv_is_tool_on_system_native_bridge": {
        "args_mapping": ["system_tool"],
        "inputs": [
            "brctl",
            "ebtables",
            "ebtables-restore",
            "ebtables-save",
            "tc",
        ],
    },
    "brv_is_tool_on_system_opensync": {
        "args_mapping": ["system_tool"],
        "inputs": list(set(opensync_required_system_tools + opensync_required_busybox_builtins)),
    },
    "brv_is_tool_on_system_ovs_bridge": {
        "args_mapping": ["system_tool"],
        "inputs": [
            "ovs-appctl",
            "ovs-dpctl",
            "ovs-ofctl",
            "ovs-vsctl",
            "ovs-vswitchd",
            "ovsdb-server",
        ],
    },
    "brv_ovs_check_version": {},
}
