test_inputs = {
    "sm_dynamic_noise_floor": {
        "default": {
            "mqtt_topic": "sm_dynamic_noise_floor",
            "sm_report_type": "raw",
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "on-chan",
            "stats_type": "survey",
            "sm_reporting_count": 0,
        },
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
            "sm_radio_type",
            "noise_range_dbm",
        ],
        "inputs": [
            [6, "HT40", "24g", "2.4G", (-120, 0)],
            [44, "HT40", "5g", "5G", (-120, 0)],
            [157, "HT40", "5g", "5G", (-120, 0)],
            [44, "HT40", "5gl", "5GL", (-120, 0)],
            [157, "HT40", "5gu", "5GU", (-120, 0)],
            [5, "HT40", "6g", "6G", (-120, 0)],
            [149, "HT40", "6g", "6G", (-120, 0)],
        ],
    },
    "sm_leaf_report": {
        "default": {
            "sm_report_type": "raw",
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "on-chan",
            "stats_type": "client",
            "mqtt_topic": "sm_leaf_report",
            "sm_reporting_count": 0,
        },
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
            "sm_radio_type",
            "encryption",
        ],
        "inputs": [
            [6, "HT40", "24g", "2.4G", "WPA2"],
            [44, "HT40", "5g", "5G", "WPA2"],
            [157, "HT40", "5g", "5G", "WPA2"],
            [44, "HT40", "5gl", "5GL", "WPA2"],
            [157, "HT40", "5gu", "5GU", "WPA2"],
            [6, "HT40", "24g", "2.4G", "WPA3"],
            [44, "HT40", "5g", "5G", "WPA3"],
            [157, "HT40", "5g", "5G", "WPA3"],
            [44, "HT40", "5gl", "5GL", "WPA3"],
            [157, "HT40", "5gu", "5GU", "WPA3"],
            [5, "HT40", "6g", "6G", "WPA3"],
            [149, "HT40", "6g", "6G", "WPA3"],
        ],
    },
    "sm_neighbor_report": {
        "default": {
            "neighbors_stats_type": "neighbor",
            "sm_report_type": "raw",
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "sm_survey_type": "on-chan",
            "survey_stats_type": "survey",
            "mqtt_topic": "sm_neighbor_report",
            "sm_reporting_count": 0,
        },
        "args_mapping": [
            "channel",
            "sm_channel",
            "ht_mode",
            "radio_band",
            "sm_radio_type",
            "encryption",
        ],
        "inputs": [
            [6, 6, "HT40", "24g", "2.4G", "WPA2"],
            [44, 44, "HT40", "5g", "5G", "WPA2"],
            [157, 157, "HT40", "5g", "5G", "WPA2"],
            [44, 44, "HT40", "5gl", "5GL", "WPA2"],
            [157, 157, "HT40", "5gu", "5GU", "WPA2"],
            [6, 6, "HT40", "24g", "2.4G", "WPA3"],
            [44, 44, "HT40", "5g", "5G", "WPA3"],
            [157, 157, "HT40", "5g", "5G", "WPA3"],
            [44, 44, "HT40", "5gl", "5GL", "WPA3"],
            [157, 157, "HT40", "5gu", "5GU", "WPA3"],
            [5, 5, "HT40", "6g", "6G", "WPA3"],
            [149, 149, "HT40", "6g", "6G", "WPA3"],
        ],
    },
    "sm_survey_report": {
        "default": {
            "sm_report_type": "raw",
            "sm_reporting_interval": 10,
            "sm_sampling_interval": 5,
            "stats_type": "survey",
            "mqtt_topic": "sm_survey_report",
            "sm_reporting_count": 0,
        },
        "args_mapping": [
            "channel",
            "sm_channel",
            "ht_mode",
            "radio_band",
            "sm_radio_type",
            "encryption",
            "sm_survey_type",
        ],
        "inputs": [
            [6, 6, "HT40", "24g", "2.4G", "WPA2", "on-chan"],
            [44, 44, "HT40", "5g", "5G", "WPA2", "on-chan"],
            [157, 157, "HT40", "5g", "5G", "WPA2", "on-chan"],
            [44, 44, "HT40", "5gl", "5GL", "WPA2", "on-chan"],
            [157, 157, "HT40", "5gu", "5GU", "WPA2", "on-chan"],
            [5, 5, "HT40", "6g", "6G", "WPA3", "on-chan"],
            [149, 149, "HT40", "6g", "6G", "WPA3", "on-chan"],
            [6, 1, "HT40", "24g", "2.4G", "WPA2", "off-chan"],
            [44, 157, "HT40", "5g", "5G", "WPA2", "off-chan"],
            [157, 44, "HT40", "5g", "5G", "WPA2", "off-chan"],
            [44, 60, "HT40", "5gl", "5GL", "WPA2", "off-chan"],
            [157, 108, "HT40", "5gu", "5GU", "WPA2", "off-chan"],
            [5, 149, "HT40", "6g", "6G", "WPA3", "off-chan"],
            [149, 5, "HT40", "6g", "6G", "WPA3", "off-chan"],
        ],
    },
}
