test_inputs = {
    "wm2_check_wpa3_with_wpa2_multi_psk": {
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
        ],
        "inputs": [
            [6, "HT40", "24g"],
            [44, "HT40", "5g"],
            [157, "HT40", "5g"],
            [44, "HT40", "5gl"],
            [157, "HT40", "5gu"],
            [5, "HT40", "6g"],
            [149, "HT40", "6g"],
        ],
    },
    "wm2_check_wifi_credential_config": {},
    "wm2_connect_wpa3_client": {
        "default": {
            "encryption": "WPA3",
        },
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
        ],
        "inputs": [
            [6, "HT40", "24g"],
            [44, "HT40", "5g"],
            [157, "HT40", "5g"],
            [44, "HT40", "5gl"],
            [157, "HT40", "5gu"],
            [5, "HT40", "6g"],
            [149, "HT40", "6g"],
        ],
    },
    "wm2_connect_wpa3_leaf": {
        "default": {
            "encryption": "WPA3",
        },
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
        ],
        "inputs": [
            [6, "HT40", "24g"],
            [44, "HT40", "5g"],
            [157, "HT40", "5g"],
            [44, "HT40", "5gl"],
            [157, "HT40", "5gu"],
            [5, "HT40", "6g"],
            [149, "HT40", "6g"],
        ],
    },
    "wm2_create_all_aps_per_radio": {
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
            "if_list",
        ],
        "inputs": [
            [
                6,
                "HT40",
                "24g",
                [
                    "backhaul_ap",
                    "home_ap",
                    "onboard_ap",
                    "aux_1_ap",
                    "aux_2_ap",
                    "fhaul_ap",
                    "cportal_ap",
                ],
            ],
            [
                44,
                "HT40",
                "5g",
                [
                    "backhaul_ap",
                    "home_ap",
                    "onboard_ap",
                    "aux_1_ap",
                    "aux_2_ap",
                    "fhaul_ap",
                    "cportal_ap",
                ],
            ],
            [
                44,
                "HT40",
                "5gl",
                [
                    "backhaul_ap",
                    "home_ap",
                    "onboard_ap",
                    "aux_1_ap",
                    "aux_2_ap",
                    "fhaul_ap",
                    "cportal_ap",
                ],
            ],
            [
                157,
                "HT40",
                "5gu",
                [
                    "backhaul_ap",
                    "home_ap",
                    "onboard_ap",
                    "aux_1_ap",
                    "aux_2_ap",
                    "fhaul_ap",
                    "cportal_ap",
                ],
            ],
        ],
    },
    "wm2_create_wpa3_ap": {
        "default": {
            "encryption": "WPA3",
        },
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
            "interface_type",
        ],
        "inputs": [
            [6, "HT40", "24g", "home_ap"],
            [6, "HT40", "24g", "backhaul_ap"],
            [44, "HT40", "5g", "home_ap"],
            [44, "HT40", "5g", "backhaul_ap"],
            [157, "HT40", "5g", "home_ap"],
            [157, "HT40", "5g", "backhaul_ap"],
            [44, "HT40", "5gl", "home_ap"],
            [44, "HT40", "5gl", "backhaul_ap"],
            [157, "HT40", "5gu", "home_ap"],
            [157, "HT40", "5gu", "backhaul_ap"],
            [5, "HT40", "6g", "home_ap"],
            [5, "HT40", "6g", "backhaul_ap"],
            [149, "HT40", "6g", "home_ap"],
            [149, "HT40", "6g", "backhaul_ap"],
        ],
    },
    "wm2_dfs_cac_aborted": {
        "args_mapping": [
            "channel_A",
            "channel_B",
            "ht_mode",
            "radio_band",
        ],
        "inputs": [
            [52, 60, "HT40", "5g"],
            [100, 108, "HT40", "5g"],
            [52, 60, "HT40", "5gl"],
            [100, 108, "HT40", "5gu"],
        ],
    },
    "wm2_ht_mode_and_channel_iteration": {},
    "wm2_immutable_radio_freq_band": {
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
            "freq_band",
        ],
        "inputs": [
            [6, "HT40", "24g", "5G"],
            [44, "HT40", "5g", "2.4G"],
            [157, "HT40", "5g", "2.4G"],
            [44, "HT40", "5gl", "2.4G"],
            [157, "HT40", "5gu", "2.4G"],
            [5, "HT40", "6g", "2.4G"],
            [149, "HT40", "6g", "2.4G"],
        ],
    },
    "wm2_immutable_radio_hw_mode": {
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
            "custom_hw_mode",
        ],
        "inputs": [
            [6, "HT40", "24g", "11b"],
            [44, "HT40", "5g", "11n"],
            [157, "HT40", "5g", "11n"],
            [44, "HT40", "5gl", "11n"],
            [157, "HT40", "5gu", "11n"],
            [5, "HT40", "6g", "11n"],
            [149, "HT40", "6g", "11n"],
        ],
    },
    "wm2_immutable_radio_hw_type": {
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
            "hw_type",
        ],
        "inputs": [
            [6, "HT40", "24g", "randhw3254"],
            [44, "HT40", "5g", "randhw3254"],
            [157, "HT40", "5g", "randhw3254"],
            [44, "HT40", "5gl", "randhw3254"],
            [157, "HT40", "5gu", "randhw3254"],
            [5, "HT40", "6g", "randhw3254"],
            [149, "HT40", "6g", "randhw3254"],
        ],
    },
    "wm2_leaf_ht_mode_change": {
        "args_mapping": [
            "channel",
            "ht_mode",
            "custom_ht_mode",
            "radio_band",
            "encryption",
        ],
        "inputs": [
            [6, "HT40", "HT20", "24g", "WPA2"],
            [44, "HT40", "HT80", "5g", "WPA2"],
            [157, "HT40", "HT80", "5g", "WPA2"],
            [44, "HT40", "HT80", "5gl", "WPA2"],
            [157, "HT40", "HT80", "5gu", "WPA2"],
            [5, "HT40", "HT80", "6g", "WPA3"],
            [149, "HT40", "HT80", "6g", "WPA3"],
        ],
    },
    "wm2_pre_cac_channel_change_validation": {
        "args_mapping": [
            "channel_A",
            "channel_B",
            "ht_mode",
            "radio_band",
        ],
        "inputs": [
            [52, 60, "HT40", "5g"],
            [40, 60, "HT80", "5g"],
            [104, 136, "HT80", "5g"],
            [52, 60, "HT40", "5gl"],
            [40, 60, "HT80", "5gl"],
            [104, 136, "HT80", "5gu"],
        ],
    },
    "wm2_pre_cac_ht_mode_change_validation": {
        "args_mapping": [
            "channel",
            "ht_mode_a",
            "ht_mode_b",
            "radio_band",
        ],
        "inputs": [
            [52, "HT80", "HT40", "5g"],
            [40, "HT80", "HT40", "5g"],
            [104, "HT80", "HT40", "5g"],
            [52, "HT80", "HT40", "5gl"],
            [40, "HT80", "HT40", "5gl"],
            [104, "HT80", "HT40", "5gu"],
        ],
    },
    "wm2_set_bcn_int": {},
    "wm2_set_channel": {},
    "wm2_set_channel_neg": {
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
            "mismatch_channel",
        ],
        "inputs": [
            [6, "HT40", "24g", [36, 123]],
            [44, "HT40", "5g", [1, 11]],
            [44, "HT40", "5gl", [1, 157]],
            [157, "HT40", "5g", [1, 11]],
            [157, "HT40", "5gu", [1, 36]],
            [5, "HT40", "6g", [3, 111]],
            [149, "HT40", "6g", [3, 111]],
        ],
    },
    "wm2_set_ht_mode": {},
    "wm2_set_ht_mode_neg": {
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
            "mismatch_ht_mode",
        ],
        "inputs": [
            [6, "HT40", "24g", "HT160"],
            [44, "HT40", "5g", "HT160"],
            [44, "HT40", "5gl", "HT160"],
            [157, "HT40", "5g", "HT160"],
            [157, "HT40", "5gu", "HT160"],
            [5, "HT40", "6g", "HT160"],
            [149, "HT40", "6g", "HT160"],
        ],
    },
    "wm2_set_radio_country": {
        "default": {
            "country": "US",
        },
        "args_mapping": [
            "radio_band",
        ],
        "inputs": [
            "24g",
            "5g",
            "5gl",
            "5gu",
            "6g",
        ],
    },
    "wm2_set_radio_thermal_tx_chainmask": {
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
        ],
        "inputs": [
            [6, "HT40", "24g"],
            [44, "HT40", "5g"],
            [157, "HT40", "5g"],
            [44, "HT40", "5gl"],
            [157, "HT40", "5gu"],
            [5, "HT40", "6g"],
            [149, "HT40", "6g"],
        ],
    },
    "wm2_set_radio_tx_chainmask": {
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
        ],
        "inputs": [
            [6, "HT40", "24g"],
            [44, "HT40", "5g"],
            [157, "HT40", "5g"],
            [44, "HT40", "5gl"],
            [157, "HT40", "5gu"],
            [5, "HT40", "6g"],
            [149, "HT40", "6g"],
        ],
    },
    "wm2_set_radio_tx_power": {
        "default": {
            "test_script_timeout": 20,
        },
        "args_mapping": ["channel", "ht_mode", "radio_band", "tx_power"],
        "inputs": [
            [6, "HT40", "24g", [1, 24]],
            [44, "HT40", "5g", [1, 24]],
            [157, "HT40", "5g", [1, 24]],
            [44, "HT40", "5gl", [1, 24]],
            [157, "HT40", "5gu", [1, 24]],
            [5, "HT40", "6g", [1, 24]],
            [149, "HT40", "6g", [1, 24]],
        ],
    },
    "wm2_set_radio_tx_power_neg": {
        "default": {
            "test_script_timeout": 20,
            "tx_power": 1,
            "mismatch_tx_power": 32,
        },
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
        ],
        "inputs": [
            [6, "HT40", "24g"],
            [44, "HT40", "5g"],
            [157, "HT40", "5g"],
            [44, "HT40", "5gl"],
            [157, "HT40", "5gu"],
            [5, "HT40", "6g"],
            [149, "HT40", "6g"],
        ],
    },
    "wm2_set_radio_vif_configs": {
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
            "custom_channel",
        ],
        "inputs": [
            [6, "HT40", "24g", 1],
            [44, "HT40", "5g", 157],
            [157, "HT40", "5g", 44],
            [44, "HT40", "5gl", 60],
            [157, "HT40", "5gu", 140],
            [5, "HT40", "6g", 149],
            [149, "HT40", "6g", 5],
        ],
    },
    "wm2_set_ssid": {
        "default": {},
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
            "ssid",
        ],
        "inputs": [
            [
                6,
                "HT40",
                "24g",
                [
                    "plus+",
                    "minus-",
                    "asterisk*",
                    "hash#",
                    "question_mark?",
                    "backslash\\",
                    "emoji👍",
                    "cyrilicГДИѲЛ",
                    "arabic٤ټٽ",
                    "hebrewאב",
                    "japanese飾り羽",
                    "special[\\T/]",
                    "ssid with spaces",
                    "a",
                    "ssidsbetweenoneandthirtytwobytes",
                ],
            ],
            [
                44,
                "HT40",
                "5g",
                [
                    "plus+",
                    "minus-",
                    "asterisk*",
                    "hash#",
                    "question_mark?",
                    "backslash\\",
                    "emoji👍",
                    "cyrilicГДИѲЛ",
                    "arabic٤ټٽ",
                    "hebrewאב",
                    "japanese飾り羽",
                    "special[\\T/]",
                    "ssid with spaces",
                    "a",
                    "ssidsbetweenoneandthirtytwobytes",
                ],
            ],
            [
                157,
                "HT40",
                "5g",
                [
                    "plus+",
                    "minus-",
                    "asterisk*",
                    "hash#",
                    "question_mark?",
                    "backslash\\",
                    "emoji👍",
                    "cyrilicГДИѲЛ",
                    "arabic٤ټٽ",
                    "hebrewאב",
                    "japanese飾り羽",
                    "special[\\T/]",
                    "ssid with spaces",
                    "a",
                    "ssidsbetweenoneandthirtytwobytes",
                ],
            ],
            [
                44,
                "HT40",
                "5gl",
                [
                    "plus+",
                    "minus-",
                    "asterisk*",
                    "hash#",
                    "question_mark?",
                    "backslash\\",
                    "emoji👍",
                    "cyrilicГДИѲЛ",
                    "arabic٤ټٽ",
                    "hebrewאב",
                    "japanese飾り羽",
                    "special[\\T/]",
                    "ssid with spaces",
                    "a",
                    "ssidsbetweenoneandthirtytwobytes",
                ],
            ],
            [
                157,
                "HT40",
                "5gu",
                [
                    "plus+",
                    "minus-",
                    "asterisk*",
                    "hash#",
                    "question_mark?",
                    "backslash\\",
                    "emoji👍",
                    "cyrilicГДИѲЛ",
                    "arabic٤ټٽ",
                    "hebrewאב",
                    "japanese飾り羽",
                    "special[\\T/]",
                    "ssid with spaces",
                    "a",
                    "ssidsbetweenoneandthirtytwobytes",
                ],
            ],
            [
                5,
                "HT40",
                "6g",
                [
                    "plus+",
                    "minus-",
                    "asterisk*",
                    "hash#",
                    "question_mark?",
                    "backslash\\",
                    "emoji👍",
                    "cyrilicГДИѲЛ",
                    "arabic٤ټٽ",
                    "hebrewאב",
                    "japanese飾り羽",
                    "special[\\T/]",
                    "ssid with spaces",
                    "a",
                    "ssidsbetweenoneandthirtytwobytes",
                ],
            ],
            [
                149,
                "HT40",
                "6g",
                [
                    "plus+",
                    "minus-",
                    "asterisk*",
                    "hash#",
                    "question_mark?",
                    "backslash\\",
                    "emoji👍",
                    "cyrilicГДИѲЛ",
                    "arabic٤ټٽ",
                    "hebrewאב",
                    "japanese飾り羽",
                    "special[\\T/]",
                    "ssid with spaces",
                    "a",
                    "ssidsbetweenoneandthirtytwobytes",
                ],
            ],
        ],
    },
    "wm2_set_wifi_credential_config": {},
    "wm2_topology_change_change_parent_change_band_change_channel": {
        "default": {
            "ht_mode": "HT40",
        },
        "args_mapping": [
            "gw_channel",
            "gw_radio_band",
            "leaf_channel",
            "leaf_radio_band",
        ],
        "inputs": [
            [6, "24g", 44, "5g"],
            [6, "24g", 44, "5gl"],
            [6, "24g", 157, "5gu"],
            [6, "24g", 5, "6g"],
            [44, "5g", 6, "24g"],
            [44, "5g", 5, "6g"],
            [44, "5gl", 6, "24g"],
            [44, "5gl", 157, "5gu"],
            [157, "5gu", 6, "24g"],
            [157, "5gu", 44, "5gl"],
            [5, "6g", 6, "24g"],
            [5, "6g", 44, "5g"],
        ],
    },
    "wm2_topology_change_change_parent_same_band_change_channel": {
        "default": {
            "ht_mode": "HT40",
        },
        "args_mapping": [
            "gw_channel",
            "radio_band",
            "leaf_channel",
        ],
        "inputs": [
            [6, "24g", 11],
            [44, "5g", 157],
            [157, "5g", 44],
            [44, "5gl", 60],
            [157, "5gu", 124],
            [5, "6g", 149],
            [149, "6g", 5],
        ],
    },
    "wm2_topology_change_change_parent_same_band_same_channel": {
        "default": {
            "ht_mode": "HT40",
        },
        "args_mapping": [
            "channel",
            "radio_band",
        ],
        "inputs": [
            [6, "24g"],
            [44, "5g"],
            [157, "5g"],
            [44, "5gl"],
            [157, "5gu"],
            [5, "6g"],
            [149, "6g"],
        ],
    },
    "wm2_validate_radio_mac_address": {
        "args_mapping": [
            "radio_band",
        ],
        "inputs": [
            "24g",
            "5g",
            "5gl",
            "5gu",
            "6g",
        ],
    },
    "wm2_verify_associated_clients": {
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
        ],
        "inputs": [
            [6, "HT40", "24g"],
            [44, "HT40", "5g"],
            [157, "HT40", "5g"],
            [44, "HT40", "5gl"],
            [157, "HT40", "5gu"],
            [5, "HT40", "6g"],
            [149, "HT40", "6g"],
        ],
    },
    "wm2_verify_sta_send_csa": {
        "args_mapping": [
            "channel",
            "csa_channel",
            "ht_mode",
            "radio_band",
            "encryption",
        ],
        "inputs": [
            [6, 1, "HT40", "24g", "WPA2"],
            [44, 157, "HT40", "5g", "WPA2"],
            [157, 44, "HT40", "5g", "WPA2"],
            [44, 60, "HT40", "5gl", "WPA2"],
            [157, 124, "HT40", "5gu", "WPA2"],
            [5, 149, "HT40", "6g", "WPA3"],
            [149, 5, "HT40", "6g", "WPA3"],
        ],
    },
    "wm2_verify_wifi_security_modes": {
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
            "encryption",
        ],
        "inputs": [
            [6, "HT40", "24g", ["open", "WPA2", "WPA3", "WPA3-transition"]],
            [44, "HT40", "5g", ["open", "WPA2", "WPA3", "WPA3-transition"]],
            [157, "HT40", "5g", ["open", "WPA2", "WPA3", "WPA3-transition"]],
            [44, "HT40", "5gl", ["open", "WPA2", "WPA3", "WPA3-transition"]],
            [157, "HT40", "5gu", ["open", "WPA2", "WPA3", "WPA3-transition"]],
            [5, "HT40", "6g", ["WPA3"]],
            [149, "HT40", "6g", ["WPA3"]],
        ],
    },
    "wm2_wifi_security_mix_on_multiple_aps": {
        "args_mapping": [
            "channel",
            "ht_mode",
            "radio_band",
            "encryption_list",
            "if_list",
        ],
        "inputs": [
            [
                6,
                "HT40",
                "24g",
                ["WPA2", "WPA3", "open"],
                [
                    "backhaul_ap",
                    "home_ap",
                    "onboard_ap",
                    "aux_1_ap",
                    "aux_2_ap",
                    "fhaul_ap",
                    "cportal_ap",
                    "haahs_ap",
                ],
            ],
            [
                44,
                "HT40",
                "5g",
                ["WPA2", "WPA3", "open"],
                [
                    "backhaul_ap",
                    "home_ap",
                    "onboard_ap",
                    "aux_1_ap",
                    "aux_2_ap",
                    "fhaul_ap",
                    "cportal_ap",
                    "haahs_ap",
                ],
            ],
            [
                44,
                "HT40",
                "5gl",
                ["WPA2", "WPA3", "open"],
                [
                    "backhaul_ap",
                    "home_ap",
                    "onboard_ap",
                    "aux_1_ap",
                    "aux_2_ap",
                    "fhaul_ap",
                    "cportal_ap",
                    "haahs_ap",
                ],
            ],
            [
                157,
                "HT40",
                "5gu",
                ["WPA2", "WPA3", "open"],
                [
                    "backhaul_ap",
                    "home_ap",
                    "onboard_ap",
                    "aux_1_ap",
                    "aux_2_ap",
                    "fhaul_ap",
                    "cportal_ap",
                ],
            ],
        ],
    },
}
